//
// unicode_blocks/cyrillic.hpp - font_to_svg
// Vinyl Darkscratch © 2018, MIT License.
// www.queengoob.org
// 
// This file contains the following unicode blocks:
// - Cyrillic
// - Cyrillic Supplement
// - Cyrillic Extended-A
// - Cyrillic Extended-B
// - Cyrillic Extended-C
// 

#define CYRILLIC \
	genSvg(fontname, "0x0400", "CYRILLIC CAPITAL LETTER IE WITH GRAVE"); \
	genSvg(fontname, "0x0401", "CYRILLIC CAPITAL LETTER IO"); \
	genSvg(fontname, "0x0402", "CYRILLIC CAPITAL LETTER DJE"); \
	genSvg(fontname, "0x0403", "CYRILLIC CAPITAL LETTER GJE"); \
	genSvg(fontname, "0x0404", "CYRILLIC CAPITAL LETTER UKRAINIAN IE"); \
	genSvg(fontname, "0x0405", "CYRILLIC CAPITAL LETTER DZE"); \
	genSvg(fontname, "0x0406", "CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I"); \
	genSvg(fontname, "0x0407", "CYRILLIC CAPITAL LETTER YI"); \
	genSvg(fontname, "0x0408", "CYRILLIC CAPITAL LETTER JE"); \
	genSvg(fontname, "0x0409", "CYRILLIC CAPITAL LETTER LJE"); \
	genSvg(fontname, "0x040A", "CYRILLIC CAPITAL LETTER NJE"); \
	genSvg(fontname, "0x040B", "CYRILLIC CAPITAL LETTER TSHE"); \
	genSvg(fontname, "0x040C", "CYRILLIC CAPITAL LETTER KJE"); \
	genSvg(fontname, "0x040D", "CYRILLIC CAPITAL LETTER I WITH GRAVE"); \
	genSvg(fontname, "0x040E", "CYRILLIC CAPITAL LETTER SHORT U"); \
	genSvg(fontname, "0x040F", "CYRILLIC CAPITAL LETTER DZHE"); \
	genSvg(fontname, "0x0410", "CYRILLIC CAPITAL LETTER A"); \
	genSvg(fontname, "0x0411", "CYRILLIC CAPITAL LETTER BE"); \
	genSvg(fontname, "0x0412", "CYRILLIC CAPITAL LETTER VE"); \
	genSvg(fontname, "0x0413", "CYRILLIC CAPITAL LETTER GHE"); \
	genSvg(fontname, "0x0414", "CYRILLIC CAPITAL LETTER DE"); \
	genSvg(fontname, "0x0415", "CYRILLIC CAPITAL LETTER IE"); \
	genSvg(fontname, "0x0416", "CYRILLIC CAPITAL LETTER ZHE"); \
	genSvg(fontname, "0x0417", "CYRILLIC CAPITAL LETTER ZE"); \
	genSvg(fontname, "0x0418", "CYRILLIC CAPITAL LETTER I"); \
	genSvg(fontname, "0x0419", "CYRILLIC CAPITAL LETTER SHORT I"); \
	genSvg(fontname, "0x041A", "CYRILLIC CAPITAL LETTER KA"); \
	genSvg(fontname, "0x041B", "CYRILLIC CAPITAL LETTER EL"); \
	genSvg(fontname, "0x041C", "CYRILLIC CAPITAL LETTER EM"); \
	genSvg(fontname, "0x041D", "CYRILLIC CAPITAL LETTER EN"); \
	genSvg(fontname, "0x041E", "CYRILLIC CAPITAL LETTER O"); \
	genSvg(fontname, "0x041F", "CYRILLIC CAPITAL LETTER PE"); \
	genSvg(fontname, "0x0420", "CYRILLIC CAPITAL LETTER ER"); \
	genSvg(fontname, "0x0421", "CYRILLIC CAPITAL LETTER ES"); \
	genSvg(fontname, "0x0422", "CYRILLIC CAPITAL LETTER TE"); \
	genSvg(fontname, "0x0423", "CYRILLIC CAPITAL LETTER U"); \
	genSvg(fontname, "0x0424", "CYRILLIC CAPITAL LETTER EF"); \
	genSvg(fontname, "0x0425", "CYRILLIC CAPITAL LETTER HA"); \
	genSvg(fontname, "0x0426", "CYRILLIC CAPITAL LETTER TSE"); \
	genSvg(fontname, "0x0427", "CYRILLIC CAPITAL LETTER CHE"); \
	genSvg(fontname, "0x0428", "CYRILLIC CAPITAL LETTER SHA"); \
	genSvg(fontname, "0x0429", "CYRILLIC CAPITAL LETTER SHCHA"); \
	genSvg(fontname, "0x042A", "CYRILLIC CAPITAL LETTER HARD SIGN"); \
	genSvg(fontname, "0x042B", "CYRILLIC CAPITAL LETTER YERU"); \
	genSvg(fontname, "0x042C", "CYRILLIC CAPITAL LETTER SOFT SIGN"); \
	genSvg(fontname, "0x042D", "CYRILLIC CAPITAL LETTER E"); \
	genSvg(fontname, "0x042E", "CYRILLIC CAPITAL LETTER YU"); \
	genSvg(fontname, "0x042F", "CYRILLIC CAPITAL LETTER YA"); \
	genSvg(fontname, "0x0430", "CYRILLIC SMALL LETTER A"); \
	genSvg(fontname, "0x0431", "CYRILLIC SMALL LETTER BE"); \
	genSvg(fontname, "0x0432", "CYRILLIC SMALL LETTER VE"); \
	genSvg(fontname, "0x0433", "CYRILLIC SMALL LETTER GHE"); \
	genSvg(fontname, "0x0434", "CYRILLIC SMALL LETTER DE"); \
	genSvg(fontname, "0x0435", "CYRILLIC SMALL LETTER IE"); \
	genSvg(fontname, "0x0436", "CYRILLIC SMALL LETTER ZHE"); \
	genSvg(fontname, "0x0437", "CYRILLIC SMALL LETTER ZE"); \
	genSvg(fontname, "0x0438", "CYRILLIC SMALL LETTER I"); \
	genSvg(fontname, "0x0439", "CYRILLIC SMALL LETTER SHORT I"); \
	genSvg(fontname, "0x043A", "CYRILLIC SMALL LETTER KA"); \
	genSvg(fontname, "0x043B", "CYRILLIC SMALL LETTER EL"); \
	genSvg(fontname, "0x043C", "CYRILLIC SMALL LETTER EM"); \
	genSvg(fontname, "0x043D", "CYRILLIC SMALL LETTER EN"); \
	genSvg(fontname, "0x043E", "CYRILLIC SMALL LETTER O"); \
	genSvg(fontname, "0x043F", "CYRILLIC SMALL LETTER PE"); \
	genSvg(fontname, "0x0440", "CYRILLIC SMALL LETTER ER"); \
	genSvg(fontname, "0x0441", "CYRILLIC SMALL LETTER ES"); \
	genSvg(fontname, "0x0442", "CYRILLIC SMALL LETTER TE"); \
	genSvg(fontname, "0x0443", "CYRILLIC SMALL LETTER U"); \
	genSvg(fontname, "0x0444", "CYRILLIC SMALL LETTER EF"); \
	genSvg(fontname, "0x0445", "CYRILLIC SMALL LETTER HA"); \
	genSvg(fontname, "0x0446", "CYRILLIC SMALL LETTER TSE"); \
	genSvg(fontname, "0x0447", "CYRILLIC SMALL LETTER CHE"); \
	genSvg(fontname, "0x0448", "CYRILLIC SMALL LETTER SHA"); \
	genSvg(fontname, "0x0449", "CYRILLIC SMALL LETTER SHCHA"); \
	genSvg(fontname, "0x044A", "CYRILLIC SMALL LETTER HARD SIGN"); \
	genSvg(fontname, "0x044B", "CYRILLIC SMALL LETTER YERU"); \
	genSvg(fontname, "0x044C", "CYRILLIC SMALL LETTER SOFT SIGN"); \
	genSvg(fontname, "0x044D", "CYRILLIC SMALL LETTER E"); \
	genSvg(fontname, "0x044E", "CYRILLIC SMALL LETTER YU"); \
	genSvg(fontname, "0x044F", "CYRILLIC SMALL LETTER YA"); \
	genSvg(fontname, "0x0450", "CYRILLIC SMALL LETTER IE WITH GRAVE"); \
	genSvg(fontname, "0x0451", "CYRILLIC SMALL LETTER IO"); \
	genSvg(fontname, "0x0452", "CYRILLIC SMALL LETTER DJE"); \
	genSvg(fontname, "0x0453", "CYRILLIC SMALL LETTER GJE"); \
	genSvg(fontname, "0x0454", "CYRILLIC SMALL LETTER UKRAINIAN IE"); \
	genSvg(fontname, "0x0455", "CYRILLIC SMALL LETTER DZE"); \
	genSvg(fontname, "0x0456", "CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I"); \
	genSvg(fontname, "0x0457", "CYRILLIC SMALL LETTER YI"); \
	genSvg(fontname, "0x0458", "CYRILLIC SMALL LETTER JE"); \
	genSvg(fontname, "0x0459", "CYRILLIC SMALL LETTER LJE"); \
	genSvg(fontname, "0x045A", "CYRILLIC SMALL LETTER NJE"); \
	genSvg(fontname, "0x045B", "CYRILLIC SMALL LETTER TSHE"); \
	genSvg(fontname, "0x045C", "CYRILLIC SMALL LETTER KJE"); \
	genSvg(fontname, "0x045D", "CYRILLIC SMALL LETTER I WITH GRAVE"); \
	genSvg(fontname, "0x045E", "CYRILLIC SMALL LETTER SHORT U"); \
	genSvg(fontname, "0x045F", "CYRILLIC SMALL LETTER DZHE"); \
	genSvg(fontname, "0x0460", "CYRILLIC CAPITAL LETTER OMEGA"); \
	genSvg(fontname, "0x0461", "CYRILLIC SMALL LETTER OMEGA"); \
	genSvg(fontname, "0x0462", "CYRILLIC CAPITAL LETTER YAT"); \
	genSvg(fontname, "0x0463", "CYRILLIC SMALL LETTER YAT"); \
	genSvg(fontname, "0x0464", "CYRILLIC CAPITAL LETTER IOTIFIED E"); \
	genSvg(fontname, "0x0465", "CYRILLIC SMALL LETTER IOTIFIED E"); \
	genSvg(fontname, "0x0466", "CYRILLIC CAPITAL LETTER LITTLE YUS"); \
	genSvg(fontname, "0x0467", "CYRILLIC SMALL LETTER LITTLE YUS"); \
	genSvg(fontname, "0x0468", "CYRILLIC CAPITAL LETTER IOTIFIED LITTLE YUS"); \
	genSvg(fontname, "0x0469", "CYRILLIC SMALL LETTER IOTIFIED LITTLE YUS"); \
	genSvg(fontname, "0x046A", "CYRILLIC CAPITAL LETTER BIG YUS"); \
	genSvg(fontname, "0x046B", "CYRILLIC SMALL LETTER BIG YUS"); \
	genSvg(fontname, "0x046C", "CYRILLIC CAPITAL LETTER IOTIFIED BIG YUS"); \
	genSvg(fontname, "0x046D", "CYRILLIC SMALL LETTER IOTIFIED BIG YUS"); \
	genSvg(fontname, "0x046E", "CYRILLIC CAPITAL LETTER KSI"); \
	genSvg(fontname, "0x046F", "CYRILLIC SMALL LETTER KSI"); \
	genSvg(fontname, "0x0470", "CYRILLIC CAPITAL LETTER PSI"); \
	genSvg(fontname, "0x0471", "CYRILLIC SMALL LETTER PSI"); \
	genSvg(fontname, "0x0472", "CYRILLIC CAPITAL LETTER FITA"); \
	genSvg(fontname, "0x0473", "CYRILLIC SMALL LETTER FITA"); \
	genSvg(fontname, "0x0474", "CYRILLIC CAPITAL LETTER IZHITSA"); \
	genSvg(fontname, "0x0475", "CYRILLIC SMALL LETTER IZHITSA"); \
	genSvg(fontname, "0x0476", "CYRILLIC CAPITAL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT"); \
	genSvg(fontname, "0x0477", "CYRILLIC SMALL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT"); \
	genSvg(fontname, "0x0478", "CYRILLIC CAPITAL LETTER UK"); \
	genSvg(fontname, "0x0479", "CYRILLIC SMALL LETTER UK"); \
	genSvg(fontname, "0x047A", "CYRILLIC CAPITAL LETTER ROUND OMEGA"); \
	genSvg(fontname, "0x047B", "CYRILLIC SMALL LETTER ROUND OMEGA"); \
	genSvg(fontname, "0x047C", "CYRILLIC CAPITAL LETTER OMEGA WITH TITLO"); \
	genSvg(fontname, "0x047D", "CYRILLIC SMALL LETTER OMEGA WITH TITLO"); \
	genSvg(fontname, "0x047E", "CYRILLIC CAPITAL LETTER OT"); \
	genSvg(fontname, "0x047F", "CYRILLIC SMALL LETTER OT"); \
	genSvg(fontname, "0x0480", "CYRILLIC CAPITAL LETTER KOPPA"); \
	genSvg(fontname, "0x0481", "CYRILLIC SMALL LETTER KOPPA"); \
	genSvg(fontname, "0x0482", "CYRILLIC THOUSANDS SIGN"); \
	genSvg(fontname, "0x0483", "COMBINING CYRILLIC TITLO"); \
	genSvg(fontname, "0x0484", "COMBINING CYRILLIC PALATALIZATION"); \
	genSvg(fontname, "0x0485", "COMBINING CYRILLIC DASIA PNEUMATA"); \
	genSvg(fontname, "0x0486", "COMBINING CYRILLIC PSILI PNEUMATA"); \
	genSvg(fontname, "0x0487", "COMBINING CYRILLIC POKRYTIE"); \
	genSvg(fontname, "0x0488", "COMBINING CYRILLIC HUNDRED THOUSANDS SIGN"); \
	genSvg(fontname, "0x0489", "COMBINING CYRILLIC MILLIONS SIGN"); \
	genSvg(fontname, "0x048A", "CYRILLIC CAPITAL LETTER SHORT I WITH TAIL"); \
	genSvg(fontname, "0x048B", "CYRILLIC SMALL LETTER SHORT I WITH TAIL"); \
	genSvg(fontname, "0x048C", "CYRILLIC CAPITAL LETTER SEMISOFT SIGN"); \
	genSvg(fontname, "0x048D", "CYRILLIC SMALL LETTER SEMISOFT SIGN"); \
	genSvg(fontname, "0x048E", "CYRILLIC CAPITAL LETTER ER WITH TICK"); \
	genSvg(fontname, "0x048F", "CYRILLIC SMALL LETTER ER WITH TICK"); \
	genSvg(fontname, "0x0490", "CYRILLIC CAPITAL LETTER GHE WITH UPTURN"); \
	genSvg(fontname, "0x0491", "CYRILLIC SMALL LETTER GHE WITH UPTURN"); \
	genSvg(fontname, "0x0492", "CYRILLIC CAPITAL LETTER GHE WITH STROKE"); \
	genSvg(fontname, "0x0493", "CYRILLIC SMALL LETTER GHE WITH STROKE"); \
	genSvg(fontname, "0x0494", "CYRILLIC CAPITAL LETTER GHE WITH MIDDLE HOOK"); \
	genSvg(fontname, "0x0495", "CYRILLIC SMALL LETTER GHE WITH MIDDLE HOOK"); \
	genSvg(fontname, "0x0496", "CYRILLIC CAPITAL LETTER ZHE WITH DESCENDER"); \
	genSvg(fontname, "0x0497", "CYRILLIC SMALL LETTER ZHE WITH DESCENDER"); \
	genSvg(fontname, "0x0498", "CYRILLIC CAPITAL LETTER ZE WITH DESCENDER"); \
	genSvg(fontname, "0x0499", "CYRILLIC SMALL LETTER ZE WITH DESCENDER"); \
	genSvg(fontname, "0x049A", "CYRILLIC CAPITAL LETTER KA WITH DESCENDER"); \
	genSvg(fontname, "0x049B", "CYRILLIC SMALL LETTER KA WITH DESCENDER"); \
	genSvg(fontname, "0x049C", "CYRILLIC CAPITAL LETTER KA WITH VERTICAL STROKE"); \
	genSvg(fontname, "0x049D", "CYRILLIC SMALL LETTER KA WITH VERTICAL STROKE"); \
	genSvg(fontname, "0x049E", "CYRILLIC CAPITAL LETTER KA WITH STROKE"); \
	genSvg(fontname, "0x049F", "CYRILLIC SMALL LETTER KA WITH STROKE"); \
	genSvg(fontname, "0x04A0", "CYRILLIC CAPITAL LETTER BASHKIR KA"); \
	genSvg(fontname, "0x04A1", "CYRILLIC SMALL LETTER BASHKIR KA"); \
	genSvg(fontname, "0x04A2", "CYRILLIC CAPITAL LETTER EN WITH DESCENDER"); \
	genSvg(fontname, "0x04A3", "CYRILLIC SMALL LETTER EN WITH DESCENDER"); \
	genSvg(fontname, "0x04A4", "CYRILLIC CAPITAL LIGATURE EN GHE"); \
	genSvg(fontname, "0x04A5", "CYRILLIC SMALL LIGATURE EN GHE"); \
	genSvg(fontname, "0x04A6", "CYRILLIC CAPITAL LETTER PE WITH MIDDLE HOOK"); \
	genSvg(fontname, "0x04A7", "CYRILLIC SMALL LETTER PE WITH MIDDLE HOOK"); \
	genSvg(fontname, "0x04A8", "CYRILLIC CAPITAL LETTER ABKHAZIAN HA"); \
	genSvg(fontname, "0x04A9", "CYRILLIC SMALL LETTER ABKHAZIAN HA"); \
	genSvg(fontname, "0x04AA", "CYRILLIC CAPITAL LETTER ES WITH DESCENDER"); \
	genSvg(fontname, "0x04AB", "CYRILLIC SMALL LETTER ES WITH DESCENDER"); \
	genSvg(fontname, "0x04AC", "CYRILLIC CAPITAL LETTER TE WITH DESCENDER"); \
	genSvg(fontname, "0x04AD", "CYRILLIC SMALL LETTER TE WITH DESCENDER"); \
	genSvg(fontname, "0x04AE", "CYRILLIC CAPITAL LETTER STRAIGHT U"); \
	genSvg(fontname, "0x04AF", "CYRILLIC SMALL LETTER STRAIGHT U"); \
	genSvg(fontname, "0x04B0", "CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE"); \
	genSvg(fontname, "0x04B1", "CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE"); \
	genSvg(fontname, "0x04B2", "CYRILLIC CAPITAL LETTER HA WITH DESCENDER"); \
	genSvg(fontname, "0x04B3", "CYRILLIC SMALL LETTER HA WITH DESCENDER"); \
	genSvg(fontname, "0x04B4", "CYRILLIC CAPITAL LIGATURE TE TSE"); \
	genSvg(fontname, "0x04B5", "CYRILLIC SMALL LIGATURE TE TSE"); \
	genSvg(fontname, "0x04B6", "CYRILLIC CAPITAL LETTER CHE WITH DESCENDER"); \
	genSvg(fontname, "0x04B7", "CYRILLIC SMALL LETTER CHE WITH DESCENDER"); \
	genSvg(fontname, "0x04B8", "CYRILLIC CAPITAL LETTER CHE WITH VERTICAL STROKE"); \
	genSvg(fontname, "0x04B9", "CYRILLIC SMALL LETTER CHE WITH VERTICAL STROKE"); \
	genSvg(fontname, "0x04BA", "CYRILLIC CAPITAL LETTER SHHA"); \
	genSvg(fontname, "0x04BB", "CYRILLIC SMALL LETTER SHHA"); \
	genSvg(fontname, "0x04BC", "CYRILLIC CAPITAL LETTER ABKHAZIAN CHE"); \
	genSvg(fontname, "0x04BD", "CYRILLIC SMALL LETTER ABKHAZIAN CHE"); \
	genSvg(fontname, "0x04BE", "CYRILLIC CAPITAL LETTER ABKHAZIAN CHE WITH DESCENDER"); \
	genSvg(fontname, "0x04BF", "CYRILLIC SMALL LETTER ABKHAZIAN CHE WITH DESCENDER"); \
	genSvg(fontname, "0x04C0", "CYRILLIC LETTER PALOCHKA"); \
	genSvg(fontname, "0x04C1", "CYRILLIC CAPITAL LETTER ZHE WITH BREVE"); \
	genSvg(fontname, "0x04C2", "CYRILLIC SMALL LETTER ZHE WITH BREVE"); \
	genSvg(fontname, "0x04C3", "CYRILLIC CAPITAL LETTER KA WITH HOOK"); \
	genSvg(fontname, "0x04C4", "CYRILLIC SMALL LETTER KA WITH HOOK"); \
	genSvg(fontname, "0x04C5", "CYRILLIC CAPITAL LETTER EL WITH TAIL"); \
	genSvg(fontname, "0x04C6", "CYRILLIC SMALL LETTER EL WITH TAIL"); \
	genSvg(fontname, "0x04C7", "CYRILLIC CAPITAL LETTER EN WITH HOOK"); \
	genSvg(fontname, "0x04C8", "CYRILLIC SMALL LETTER EN WITH HOOK"); \
	genSvg(fontname, "0x04C9", "CYRILLIC CAPITAL LETTER EN WITH TAIL"); \
	genSvg(fontname, "0x04CA", "CYRILLIC SMALL LETTER EN WITH TAIL"); \
	genSvg(fontname, "0x04CB", "CYRILLIC CAPITAL LETTER KHAKASSIAN CHE"); \
	genSvg(fontname, "0x04CC", "CYRILLIC SMALL LETTER KHAKASSIAN CHE"); \
	genSvg(fontname, "0x04CD", "CYRILLIC CAPITAL LETTER EM WITH TAIL"); \
	genSvg(fontname, "0x04CE", "CYRILLIC SMALL LETTER EM WITH TAIL"); \
	genSvg(fontname, "0x04CF", "CYRILLIC SMALL LETTER PALOCHKA"); \
	genSvg(fontname, "0x04D0", "CYRILLIC CAPITAL LETTER A WITH BREVE"); \
	genSvg(fontname, "0x04D1", "CYRILLIC SMALL LETTER A WITH BREVE"); \
	genSvg(fontname, "0x04D2", "CYRILLIC CAPITAL LETTER A WITH DIAERESIS"); \
	genSvg(fontname, "0x04D3", "CYRILLIC SMALL LETTER A WITH DIAERESIS"); \
	genSvg(fontname, "0x04D4", "CYRILLIC CAPITAL LIGATURE A IE"); \
	genSvg(fontname, "0x04D5", "CYRILLIC SMALL LIGATURE A IE"); \
	genSvg(fontname, "0x04D6", "CYRILLIC CAPITAL LETTER IE WITH BREVE"); \
	genSvg(fontname, "0x04D7", "CYRILLIC SMALL LETTER IE WITH BREVE"); \
	genSvg(fontname, "0x04D8", "CYRILLIC CAPITAL LETTER SCHWA"); \
	genSvg(fontname, "0x04D9", "CYRILLIC SMALL LETTER SCHWA"); \
	genSvg(fontname, "0x04DA", "CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS"); \
	genSvg(fontname, "0x04DB", "CYRILLIC SMALL LETTER SCHWA WITH DIAERESIS"); \
	genSvg(fontname, "0x04DC", "CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS"); \
	genSvg(fontname, "0x04DD", "CYRILLIC SMALL LETTER ZHE WITH DIAERESIS"); \
	genSvg(fontname, "0x04DE", "CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS"); \
	genSvg(fontname, "0x04DF", "CYRILLIC SMALL LETTER ZE WITH DIAERESIS"); \
	genSvg(fontname, "0x04E0", "CYRILLIC CAPITAL LETTER ABKHAZIAN DZE"); \
	genSvg(fontname, "0x04E1", "CYRILLIC SMALL LETTER ABKHAZIAN DZE"); \
	genSvg(fontname, "0x04E2", "CYRILLIC CAPITAL LETTER I WITH MACRON"); \
	genSvg(fontname, "0x04E3", "CYRILLIC SMALL LETTER I WITH MACRON"); \
	genSvg(fontname, "0x04E4", "CYRILLIC CAPITAL LETTER I WITH DIAERESIS"); \
	genSvg(fontname, "0x04E5", "CYRILLIC SMALL LETTER I WITH DIAERESIS"); \
	genSvg(fontname, "0x04E6", "CYRILLIC CAPITAL LETTER O WITH DIAERESIS"); \
	genSvg(fontname, "0x04E7", "CYRILLIC SMALL LETTER O WITH DIAERESIS"); \
	genSvg(fontname, "0x04E8", "CYRILLIC CAPITAL LETTER BARRED O"); \
	genSvg(fontname, "0x04E9", "CYRILLIC SMALL LETTER BARRED O"); \
	genSvg(fontname, "0x04EA", "CYRILLIC CAPITAL LETTER BARRED O WITH DIAERESIS"); \
	genSvg(fontname, "0x04EB", "CYRILLIC SMALL LETTER BARRED O WITH DIAERESIS"); \
	genSvg(fontname, "0x04EC", "CYRILLIC CAPITAL LETTER E WITH DIAERESIS"); \
	genSvg(fontname, "0x04ED", "CYRILLIC SMALL LETTER E WITH DIAERESIS"); \
	genSvg(fontname, "0x04EE", "CYRILLIC CAPITAL LETTER U WITH MACRON"); \
	genSvg(fontname, "0x04EF", "CYRILLIC SMALL LETTER U WITH MACRON"); \
	genSvg(fontname, "0x04F0", "CYRILLIC CAPITAL LETTER U WITH DIAERESIS"); \
	genSvg(fontname, "0x04F1", "CYRILLIC SMALL LETTER U WITH DIAERESIS"); \
	genSvg(fontname, "0x04F2", "CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE"); \
	genSvg(fontname, "0x04F3", "CYRILLIC SMALL LETTER U WITH DOUBLE ACUTE"); \
	genSvg(fontname, "0x04F4", "CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS"); \
	genSvg(fontname, "0x04F5", "CYRILLIC SMALL LETTER CHE WITH DIAERESIS"); \
	genSvg(fontname, "0x04F6", "CYRILLIC CAPITAL LETTER GHE WITH DESCENDER"); \
	genSvg(fontname, "0x04F7", "CYRILLIC SMALL LETTER GHE WITH DESCENDER"); \
	genSvg(fontname, "0x04F8", "CYRILLIC CAPITAL LETTER YERU WITH DIAERESIS"); \
	genSvg(fontname, "0x04F9", "CYRILLIC SMALL LETTER YERU WITH DIAERESIS"); \
	genSvg(fontname, "0x04FA", "CYRILLIC CAPITAL LETTER GHE WITH STROKE AND HOOK"); \
	genSvg(fontname, "0x04FB", "CYRILLIC SMALL LETTER GHE WITH STROKE AND HOOK"); \
	genSvg(fontname, "0x04FC", "CYRILLIC CAPITAL LETTER HA WITH HOOK"); \
	genSvg(fontname, "0x04FD", "CYRILLIC SMALL LETTER HA WITH HOOK"); \
	genSvg(fontname, "0x04FE", "CYRILLIC CAPITAL LETTER HA WITH STROKE"); \
	genSvg(fontname, "0x04FF", "CYRILLIC SMALL LETTER HA WITH STROKE");

#define CYRILLIC_SUPPLEMENT \
	genSvg(fontname, "0x0500", "CYRILLIC CAPITAL LETTER KOMI DE"); \
	genSvg(fontname, "0x0501", "CYRILLIC SMALL LETTER KOMI DE"); \
	genSvg(fontname, "0x0502", "CYRILLIC CAPITAL LETTER KOMI DJE"); \
	genSvg(fontname, "0x0503", "CYRILLIC SMALL LETTER KOMI DJE"); \
	genSvg(fontname, "0x0504", "CYRILLIC CAPITAL LETTER KOMI ZJE"); \
	genSvg(fontname, "0x0505", "CYRILLIC SMALL LETTER KOMI ZJE"); \
	genSvg(fontname, "0x0506", "CYRILLIC CAPITAL LETTER KOMI DZJE"); \
	genSvg(fontname, "0x0507", "CYRILLIC SMALL LETTER KOMI DZJE"); \
	genSvg(fontname, "0x0508", "CYRILLIC CAPITAL LETTER KOMI LJE"); \
	genSvg(fontname, "0x0509", "CYRILLIC SMALL LETTER KOMI LJE"); \
	genSvg(fontname, "0x050A", "CYRILLIC CAPITAL LETTER KOMI NJE"); \
	genSvg(fontname, "0x050B", "CYRILLIC SMALL LETTER KOMI NJE"); \
	genSvg(fontname, "0x050C", "CYRILLIC CAPITAL LETTER KOMI SJE"); \
	genSvg(fontname, "0x050D", "CYRILLIC SMALL LETTER KOMI SJE"); \
	genSvg(fontname, "0x050E", "CYRILLIC CAPITAL LETTER KOMI TJE"); \
	genSvg(fontname, "0x050F", "CYRILLIC SMALL LETTER KOMI TJE"); \
	genSvg(fontname, "0x0510", "CYRILLIC CAPITAL LETTER REVERSED ZE"); \
	genSvg(fontname, "0x0511", "CYRILLIC SMALL LETTER REVERSED ZE"); \
	genSvg(fontname, "0x0512", "CYRILLIC CAPITAL LETTER EL WITH HOOK"); \
	genSvg(fontname, "0x0513", "CYRILLIC SMALL LETTER EL WITH HOOK"); \
	genSvg(fontname, "0x0514", "CYRILLIC CAPITAL LETTER LHA"); \
	genSvg(fontname, "0x0515", "CYRILLIC SMALL LETTER LHA"); \
	genSvg(fontname, "0x0516", "CYRILLIC CAPITAL LETTER RHA"); \
	genSvg(fontname, "0x0517", "CYRILLIC SMALL LETTER RHA"); \
	genSvg(fontname, "0x0518", "CYRILLIC CAPITAL LETTER YAE"); \
	genSvg(fontname, "0x0519", "CYRILLIC SMALL LETTER YAE"); \
	genSvg(fontname, "0x051A", "CYRILLIC CAPITAL LETTER QA"); \
	genSvg(fontname, "0x051B", "CYRILLIC SMALL LETTER QA"); \
	genSvg(fontname, "0x051C", "CYRILLIC CAPITAL LETTER WE"); \
	genSvg(fontname, "0x051D", "CYRILLIC SMALL LETTER WE"); \
	genSvg(fontname, "0x051E", "CYRILLIC CAPITAL LETTER ALEUT KA"); \
	genSvg(fontname, "0x051F", "CYRILLIC SMALL LETTER ALEUT KA"); \
	genSvg(fontname, "0x0520", "CYRILLIC CAPITAL LETTER EL WITH MIDDLE HOOK"); \
	genSvg(fontname, "0x0521", "CYRILLIC SMALL LETTER EL WITH MIDDLE HOOK"); \
	genSvg(fontname, "0x0522", "CYRILLIC CAPITAL LETTER EN WITH MIDDLE HOOK"); \
	genSvg(fontname, "0x0523", "CYRILLIC SMALL LETTER EN WITH MIDDLE HOOK"); \
	genSvg(fontname, "0x0524", "CYRILLIC CAPITAL LETTER PE WITH DESCENDER"); \
	genSvg(fontname, "0x0525", "CYRILLIC SMALL LETTER PE WITH DESCENDER"); \
	genSvg(fontname, "0x0526", "CYRILLIC CAPITAL LETTER SHHA WITH DESCENDER"); \
	genSvg(fontname, "0x0527", "CYRILLIC SMALL LETTER SHHA WITH DESCENDER"); \
	genSvg(fontname, "0x0528", "CYRILLIC CAPITAL LETTER EN WITH LEFT HOOK"); \
	genSvg(fontname, "0x0529", "CYRILLIC SMALL LETTER EN WITH LEFT HOOK"); \
	genSvg(fontname, "0x052A", "CYRILLIC CAPITAL LETTER DZZHE"); \
	genSvg(fontname, "0x052B", "CYRILLIC SMALL LETTER DZZHE"); \
	genSvg(fontname, "0x052C", "CYRILLIC CAPITAL LETTER DCHE"); \
	genSvg(fontname, "0x052D", "CYRILLIC SMALL LETTER DCHE"); \
	genSvg(fontname, "0x052E", "CYRILLIC CAPITAL LETTER EL WITH DESCENDER"); \
	genSvg(fontname, "0x052F", "CYRILLIC SMALL LETTER EL WITH DESCENDER");

#define CYRILLIC_EXTENDED_A \
	genSvg(fontname, "0x2DE0", "COMBINING CYRILLIC LETTER BE"); \
	genSvg(fontname, "0x2DE1", "COMBINING CYRILLIC LETTER VE"); \
	genSvg(fontname, "0x2DE2", "COMBINING CYRILLIC LETTER GHE"); \
	genSvg(fontname, "0x2DE3", "COMBINING CYRILLIC LETTER DE"); \
	genSvg(fontname, "0x2DE4", "COMBINING CYRILLIC LETTER ZHE"); \
	genSvg(fontname, "0x2DE5", "COMBINING CYRILLIC LETTER ZE"); \
	genSvg(fontname, "0x2DE6", "COMBINING CYRILLIC LETTER KA"); \
	genSvg(fontname, "0x2DE7", "COMBINING CYRILLIC LETTER EL"); \
	genSvg(fontname, "0x2DE8", "COMBINING CYRILLIC LETTER EM"); \
	genSvg(fontname, "0x2DE9", "COMBINING CYRILLIC LETTER EN"); \
	genSvg(fontname, "0x2DEA", "COMBINING CYRILLIC LETTER O"); \
	genSvg(fontname, "0x2DEB", "COMBINING CYRILLIC LETTER PE"); \
	genSvg(fontname, "0x2DEC", "COMBINING CYRILLIC LETTER ER"); \
	genSvg(fontname, "0x2DED", "COMBINING CYRILLIC LETTER ES"); \
	genSvg(fontname, "0x2DEE", "COMBINING CYRILLIC LETTER TE"); \
	genSvg(fontname, "0x2DEF", "COMBINING CYRILLIC LETTER HA"); \
	genSvg(fontname, "0x2DF0", "COMBINING CYRILLIC LETTER TSE"); \
	genSvg(fontname, "0x2DF1", "COMBINING CYRILLIC LETTER CHE"); \
	genSvg(fontname, "0x2DF2", "COMBINING CYRILLIC LETTER SHA"); \
	genSvg(fontname, "0x2DF3", "COMBINING CYRILLIC LETTER SHCHA"); \
	genSvg(fontname, "0x2DF4", "COMBINING CYRILLIC LETTER FITA"); \
	genSvg(fontname, "0x2DF5", "COMBINING CYRILLIC LETTER ES-TE"); \
	genSvg(fontname, "0x2DF6", "COMBINING CYRILLIC LETTER A"); \
	genSvg(fontname, "0x2DF7", "COMBINING CYRILLIC LETTER IE"); \
	genSvg(fontname, "0x2DF8", "COMBINING CYRILLIC LETTER DJERV"); \
	genSvg(fontname, "0x2DF9", "COMBINING CYRILLIC LETTER MONOGRAPH UK"); \
	genSvg(fontname, "0x2DFA", "COMBINING CYRILLIC LETTER YAT"); \
	genSvg(fontname, "0x2DFB", "COMBINING CYRILLIC LETTER YU"); \
	genSvg(fontname, "0x2DFC", "COMBINING CYRILLIC LETTER IOTIFIED A"); \
	genSvg(fontname, "0x2DFD", "COMBINING CYRILLIC LETTER LITTLE YUS"); \
	genSvg(fontname, "0x2DFE", "COMBINING CYRILLIC LETTER BIG YUS"); \
	genSvg(fontname, "0x2DFF", "COMBINING CYRILLIC LETTER IOTIFIED BIG YUS");

#define CYRILLIC_EXTENDED_B \
	genSvg(fontname, "0xA640", "CYRILLIC CAPITAL LETTER ZEMLYA"); \
	genSvg(fontname, "0xA641", "CYRILLIC SMALL LETTER ZEMLYA"); \
	genSvg(fontname, "0xA642", "CYRILLIC CAPITAL LETTER DZELO"); \
	genSvg(fontname, "0xA643", "CYRILLIC SMALL LETTER DZELO"); \
	genSvg(fontname, "0xA644", "CYRILLIC CAPITAL LETTER REVERSED DZE"); \
	genSvg(fontname, "0xA645", "CYRILLIC SMALL LETTER REVERSED DZE"); \
	genSvg(fontname, "0xA646", "CYRILLIC CAPITAL LETTER IOTA"); \
	genSvg(fontname, "0xA647", "CYRILLIC SMALL LETTER IOTA"); \
	genSvg(fontname, "0xA648", "CYRILLIC CAPITAL LETTER DJERV"); \
	genSvg(fontname, "0xA649", "CYRILLIC SMALL LETTER DJERV"); \
	genSvg(fontname, "0xA64A", "CYRILLIC CAPITAL LETTER MONOGRAPH UK"); \
	genSvg(fontname, "0xA64B", "CYRILLIC SMALL LETTER MONOGRAPH UK"); \
	genSvg(fontname, "0xA64C", "CYRILLIC CAPITAL LETTER BROAD OMEGA"); \
	genSvg(fontname, "0xA64D", "CYRILLIC SMALL LETTER BROAD OMEGA"); \
	genSvg(fontname, "0xA64E", "CYRILLIC CAPITAL LETTER NEUTRAL YER"); \
	genSvg(fontname, "0xA64F", "CYRILLIC SMALL LETTER NEUTRAL YER"); \
	genSvg(fontname, "0xA650", "CYRILLIC CAPITAL LETTER YERU WITH BACK YER"); \
	genSvg(fontname, "0xA651", "CYRILLIC SMALL LETTER YERU WITH BACK YER"); \
	genSvg(fontname, "0xA652", "CYRILLIC CAPITAL LETTER IOTIFIED YAT"); \
	genSvg(fontname, "0xA653", "CYRILLIC SMALL LETTER IOTIFIED YAT"); \
	genSvg(fontname, "0xA654", "CYRILLIC CAPITAL LETTER REVERSED YU"); \
	genSvg(fontname, "0xA655", "CYRILLIC SMALL LETTER REVERSED YU"); \
	genSvg(fontname, "0xA656", "CYRILLIC CAPITAL LETTER IOTIFIED A"); \
	genSvg(fontname, "0xA657", "CYRILLIC SMALL LETTER IOTIFIED A"); \
	genSvg(fontname, "0xA658", "CYRILLIC CAPITAL LETTER CLOSED LITTLE YUS"); \
	genSvg(fontname, "0xA659", "CYRILLIC SMALL LETTER CLOSED LITTLE YUS"); \
	genSvg(fontname, "0xA65A", "CYRILLIC CAPITAL LETTER BLENDED YUS"); \
	genSvg(fontname, "0xA65B", "CYRILLIC SMALL LETTER BLENDED YUS"); \
	genSvg(fontname, "0xA65C", "CYRILLIC CAPITAL LETTER IOTIFIED CLOSED LITTLE YUS"); \
	genSvg(fontname, "0xA65D", "CYRILLIC SMALL LETTER IOTIFIED CLOSED LITTLE YUS"); \
	genSvg(fontname, "0xA65E", "CYRILLIC CAPITAL LETTER YN"); \
	genSvg(fontname, "0xA65F", "CYRILLIC SMALL LETTER YN"); \
	genSvg(fontname, "0xA660", "CYRILLIC CAPITAL LETTER REVERSED TSE"); \
	genSvg(fontname, "0xA661", "CYRILLIC SMALL LETTER REVERSED TSE"); \
	genSvg(fontname, "0xA662", "CYRILLIC CAPITAL LETTER SOFT DE"); \
	genSvg(fontname, "0xA663", "CYRILLIC SMALL LETTER SOFT DE"); \
	genSvg(fontname, "0xA664", "CYRILLIC CAPITAL LETTER SOFT EL"); \
	genSvg(fontname, "0xA665", "CYRILLIC SMALL LETTER SOFT EL"); \
	genSvg(fontname, "0xA666", "CYRILLIC CAPITAL LETTER SOFT EM"); \
	genSvg(fontname, "0xA667", "CYRILLIC SMALL LETTER SOFT EM"); \
	genSvg(fontname, "0xA668", "CYRILLIC CAPITAL LETTER MONOCULAR O"); \
	genSvg(fontname, "0xA669", "CYRILLIC SMALL LETTER MONOCULAR O"); \
	genSvg(fontname, "0xA66A", "CYRILLIC CAPITAL LETTER BINOCULAR O"); \
	genSvg(fontname, "0xA66B", "CYRILLIC SMALL LETTER BINOCULAR O"); \
	genSvg(fontname, "0xA66C", "CYRILLIC CAPITAL LETTER DOUBLE MONOCULAR O"); \
	genSvg(fontname, "0xA66D", "CYRILLIC SMALL LETTER DOUBLE MONOCULAR O"); \
	genSvg(fontname, "0xA66E", "CYRILLIC LETTER MULTIOCULAR O"); \
	genSvg(fontname, "0xA66F", "COMBINING CYRILLIC VZMET"); \
	genSvg(fontname, "0xA670", "COMBINING CYRILLIC TEN MILLIONS SIGN"); \
	genSvg(fontname, "0xA671", "COMBINING CYRILLIC HUNDRED MILLIONS SIGN"); \
	genSvg(fontname, "0xA672", "COMBINING CYRILLIC THOUSAND MILLIONS SIGN"); \
	genSvg(fontname, "0xA673", "SLAVONIC ASTERISK"); \
	genSvg(fontname, "0xA674", "COMBINING CYRILLIC LETTER UKRAINIAN IE"); \
	genSvg(fontname, "0xA675", "COMBINING CYRILLIC LETTER I"); \
	genSvg(fontname, "0xA676", "COMBINING CYRILLIC LETTER YI"); \
	genSvg(fontname, "0xA677", "COMBINING CYRILLIC LETTER U"); \
	genSvg(fontname, "0xA678", "COMBINING CYRILLIC LETTER HARD SIGN"); \
	genSvg(fontname, "0xA679", "COMBINING CYRILLIC LETTER YERU"); \
	genSvg(fontname, "0xA67A", "COMBINING CYRILLIC LETTER SOFT SIGN"); \
	genSvg(fontname, "0xA67B", "COMBINING CYRILLIC LETTER OMEGA"); \
	genSvg(fontname, "0xA67C", "COMBINING CYRILLIC KAVYKA"); \
	genSvg(fontname, "0xA67D", "COMBINING CYRILLIC PAYEROK"); \
	genSvg(fontname, "0xA67E", "CYRILLIC KAVYKA"); \
	genSvg(fontname, "0xA67F", "CYRILLIC PAYEROK"); \
	genSvg(fontname, "0xA680", "CYRILLIC CAPITAL LETTER DWE"); \
	genSvg(fontname, "0xA681", "CYRILLIC SMALL LETTER DWE"); \
	genSvg(fontname, "0xA682", "CYRILLIC CAPITAL LETTER DZWE"); \
	genSvg(fontname, "0xA683", "CYRILLIC SMALL LETTER DZWE"); \
	genSvg(fontname, "0xA684", "CYRILLIC CAPITAL LETTER ZHWE"); \
	genSvg(fontname, "0xA685", "CYRILLIC SMALL LETTER ZHWE"); \
	genSvg(fontname, "0xA686", "CYRILLIC CAPITAL LETTER CCHE"); \
	genSvg(fontname, "0xA687", "CYRILLIC SMALL LETTER CCHE"); \
	genSvg(fontname, "0xA688", "CYRILLIC CAPITAL LETTER DZZE"); \
	genSvg(fontname, "0xA689", "CYRILLIC SMALL LETTER DZZE"); \
	genSvg(fontname, "0xA68A", "CYRILLIC CAPITAL LETTER TE WITH MIDDLE HOOK"); \
	genSvg(fontname, "0xA68B", "CYRILLIC SMALL LETTER TE WITH MIDDLE HOOK"); \
	genSvg(fontname, "0xA68C", "CYRILLIC CAPITAL LETTER TWE"); \
	genSvg(fontname, "0xA68D", "CYRILLIC SMALL LETTER TWE"); \
	genSvg(fontname, "0xA68E", "CYRILLIC CAPITAL LETTER TSWE"); \
	genSvg(fontname, "0xA68F", "CYRILLIC SMALL LETTER TSWE"); \
	genSvg(fontname, "0xA690", "CYRILLIC CAPITAL LETTER TSSE"); \
	genSvg(fontname, "0xA691", "CYRILLIC SMALL LETTER TSSE"); \
	genSvg(fontname, "0xA692", "CYRILLIC CAPITAL LETTER TCHE"); \
	genSvg(fontname, "0xA693", "CYRILLIC SMALL LETTER TCHE"); \
	genSvg(fontname, "0xA694", "CYRILLIC CAPITAL LETTER HWE"); \
	genSvg(fontname, "0xA695", "CYRILLIC SMALL LETTER HWE"); \
	genSvg(fontname, "0xA696", "CYRILLIC CAPITAL LETTER SHWE"); \
	genSvg(fontname, "0xA697", "CYRILLIC SMALL LETTER SHWE"); \
	genSvg(fontname, "0xA698", "CYRILLIC CAPITAL LETTER DOUBLE O"); \
	genSvg(fontname, "0xA699", "CYRILLIC SMALL LETTER DOUBLE O"); \
	genSvg(fontname, "0xA69A", "CYRILLIC CAPITAL LETTER CROSSED O"); \
	genSvg(fontname, "0xA69B", "CYRILLIC SMALL LETTER CROSSED O"); \
	genSvg(fontname, "0xA69C", "MODIFIER LETTER CYRILLIC HARD SIGN"); \
	genSvg(fontname, "0xA69D", "MODIFIER LETTER CYRILLIC SOFT SIGN"); \
	genSvg(fontname, "0xA69E", "COMBINING CYRILLIC LETTER EF"); \
	genSvg(fontname, "0xA69F", "COMBINING CYRILLIC LETTER IOTIFIED E");

#define CYRILLIC_EXTENDED_C \
	genSvg(fontname, "0x1C80", "CYRILLIC SMALL LETTER ROUNDED VE"); \
	genSvg(fontname, "0x1C81", "CYRILLIC SMALL LETTER LONG-LEGGED DE"); \
	genSvg(fontname, "0x1C82", "CYRILLIC SMALL LETTER NARROW O"); \
	genSvg(fontname, "0x1C83", "CYRILLIC SMALL LETTER WIDE ES"); \
	genSvg(fontname, "0x1C84", "CYRILLIC SMALL LETTER TALL TE"); \
	genSvg(fontname, "0x1C85", "CYRILLIC SMALL LETTER THREE-LEGGED TE"); \
	genSvg(fontname, "0x1C86", "CYRILLIC SMALL LETTER TALL HARD SIGN"); \
	genSvg(fontname, "0x1C87", "CYRILLIC SMALL LETTER TALL YAT"); \
	genSvg(fontname, "0x1C88", "CYRILLIC SMALL LETTER UNBLENDED UK");
