//
// unicode_blocks/greek_and_coptic.hpp - font_to_svg
// Vinyl Darkscratch © 2018, MIT License.
// www.queengoob.org
// 
// Unicode Standard Version: 11.0
// This file contains the following unicode blocks:
// - Greek and Coptic
// - Greek Extended
// 

#define GREEK_AND_COPTIC \
	genSvg(fontname, "0x0370", "GREEK CAPITAL LETTER HETA"); \
	genSvg(fontname, "0x0371", "GREEK SMALL LETTER HETA"); \
	genSvg(fontname, "0x0372", "GREEK CAPITAL LETTER ARCHAIC SAMPI"); \
	genSvg(fontname, "0x0373", "GREEK SMALL LETTER ARCHAIC SAMPI"); \
	genSvg(fontname, "0x0374", "GREEK NUMERAL SIGN"); \
	genSvg(fontname, "0x0375", "GREEK LOWER NUMERAL SIGN"); \
	genSvg(fontname, "0x0376", "GREEK CAPITAL LETTER PAMPHYLIAN DIGAMMA"); \
	genSvg(fontname, "0x0377", "GREEK SMALL LETTER PAMPHYLIAN DIGAMMA"); \
	genSvg(fontname, "0x037A", "GREEK YPOGEGRAMMENI"); \
	genSvg(fontname, "0x037B", "GREEK SMALL REVERSED LUNATE SIGMA SYMBOL"); \
	genSvg(fontname, "0x037C", "GREEK SMALL DOTTED LUNATE SIGMA SYMBOL"); \
	genSvg(fontname, "0x037D", "GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL"); \
	genSvg(fontname, "0x037E", "GREEK QUESTION MARK"); \
	genSvg(fontname, "0x037F", "GREEK CAPITAL LETTER YOT"); \
	genSvg(fontname, "0x0384", "GREEK ACUTE ACCENT (TONOS)"); \
	genSvg(fontname, "0x0385", "GREEK DIAERESIS WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x0386", "GREEK CAPITAL LETTER A WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x0387", "GREEK ANO TELEIA"); \
	genSvg(fontname, "0x0388", "GREEK CAPITAL LETTER EPSILON WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x0389", "GREEK CAPITAL LETTER ETA WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x038A", "GREEK CAPITAL LETTER IOTA WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x038C", "GREEK CAPITAL LETTER OMICRON WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x038E", "GREEK CAPITAL LETTER UPSILON WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x038F", "GREEK CAPITAL LETTER OMEGA WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x0390", "GREEK SMALL LETTER IOTA WITH DIAERESIS AND ACUTE ACCENT"); \
	genSvg(fontname, "0x0391", "GREEK CAPITAL LETTER ALPHA"); \
	genSvg(fontname, "0x0392", "GREEK CAPITAL LETTER BETA"); \
	genSvg(fontname, "0x0393", "GREEK CAPITAL LETTER GAMMA"); \
	genSvg(fontname, "0x0394", "GREEK CAPITAL LETTER DELTA"); \
	genSvg(fontname, "0x0395", "GREEK CAPITAL LETTER EPSILON"); \
	genSvg(fontname, "0x0396", "GREEK CAPITAL LETTER ZETA"); \
	genSvg(fontname, "0x0397", "GREEK CAPITAL LETTER ETA"); \
	genSvg(fontname, "0x0398", "GREEK CAPITAL LETTER THETA"); \
	genSvg(fontname, "0x0399", "GREEK CAPITAL LETTER IOTA"); \
	genSvg(fontname, "0x039A", "GREEK CAPITAL LETTER KAPPA"); \
	genSvg(fontname, "0x039B", "GREEK CAPITAL LETTER LAMBDA"); \
	genSvg(fontname, "0x039C", "GREEK CAPITAL LETTER MU"); \
	genSvg(fontname, "0x039D", "GREEK CAPITAL LETTER NU"); \
	genSvg(fontname, "0x039E", "GREEK CAPITAL LETTER XI"); \
	genSvg(fontname, "0x039F", "GREEK CAPITAL LETTER OMICRON"); \
	genSvg(fontname, "0x03A0", "GREEK CAPITAL LETTER PI"); \
	genSvg(fontname, "0x03A1", "GREEK CAPITAL LETTER RHO"); \
	genSvg(fontname, "0x03A3", "GREEK CAPITAL LETTER SIGMA"); \
	genSvg(fontname, "0x03A4", "GREEK CAPITAL LETTER TAU"); \
	genSvg(fontname, "0x03A5", "GREEK CAPITAL LETTER UPSILON"); \
	genSvg(fontname, "0x03A6", "GREEK CAPITAL LETTER PHI"); \
	genSvg(fontname, "0x03A7", "GREEK CAPITAL LETTER CHI"); \
	genSvg(fontname, "0x03A8", "GREEK CAPITAL LETTER PSI"); \
	genSvg(fontname, "0x03A9", "GREEK CAPITAL LETTER OMEGA"); \
	genSvg(fontname, "0x03AA", "GREEK CAPITAL LETTER IOTA WITH DIAERESIS"); \
	genSvg(fontname, "0x03AB", "GREEK CAPITAL LETTER UPSILON WITH DIAERESIS"); \
	genSvg(fontname, "0x03AC", "GREEK SMALL LETTER ALPHA WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x03AD", "GREEK SMALL LETTER EPSILON WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x03AE", "GREEK SMALL LETTER ETA WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x03AF", "GREEK SMALL LETTER IOTA WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x03B0", "GREEK SMALL LETTER UPSILON WITH DIAERESIS AND ACUTE ACCENT"); \
	genSvg(fontname, "0x03B1", "GREEK SMALL LETTER ALPHA"); \
	genSvg(fontname, "0x03B2", "GREEK SMALL LETTER BETA"); \
	genSvg(fontname, "0x03B3", "GREEK SMALL LETTER GAMMA"); \
	genSvg(fontname, "0x03B4", "GREEK SMALL LETTER DELTA"); \
	genSvg(fontname, "0x03B5", "GREEK SMALL LETTER EPSILON"); \
	genSvg(fontname, "0x03B6", "GREEK SMALL LETTER ZETA"); \
	genSvg(fontname, "0x03B7", "GREEK SMALL LETTER ETA"); \
	genSvg(fontname, "0x03B8", "GREEK SMALL LETTER THETA"); \
	genSvg(fontname, "0x03B9", "GREEK SMALL LETTER IOTA"); \
	genSvg(fontname, "0x03BA", "GREEK SMALL LETTER KAPPA"); \
	genSvg(fontname, "0x03BB", "GREEK SMALL LETTER LAMBDA"); \
	genSvg(fontname, "0x03BC", "GREEK SMALL LETTER MU"); \
	genSvg(fontname, "0x03BD", "GREEK SMALL LETTER NU"); \
	genSvg(fontname, "0x03BE", "GREEK SMALL LETTER XI"); \
	genSvg(fontname, "0x03BF", "GREEK SMALL LETTER OMICRON"); \
	genSvg(fontname, "0x03C0", "GREEK SMALL LETTER PI"); \
	genSvg(fontname, "0x03C1", "GREEK SMALL LETTER RHO"); \
	genSvg(fontname, "0x03C2", "GREEK SMALL LETTER FINAL SIGMA"); \
	genSvg(fontname, "0x03C3", "GREEK SMALL LETTER SIGMA"); \
	genSvg(fontname, "0x03C4", "GREEK SMALL LETTER TAU"); \
	genSvg(fontname, "0x03C5", "GREEK SMALL LETTER UPSILON"); \
	genSvg(fontname, "0x03C6", "GREEK SMALL LETTER PHI"); \
	genSvg(fontname, "0x03C7", "GREEK SMALL LETTER CHI"); \
	genSvg(fontname, "0x03C8", "GREEK SMALL LETTER PSI"); \
	genSvg(fontname, "0x03C9", "GREEK SMALL LETTER OMEGA"); \
	genSvg(fontname, "0x03CA", "GREEK SMALL LETTER IOTA WITH DIAERESIS"); \
	genSvg(fontname, "0x03CB", "GREEK SMALL LETTER UPSILON WITH DIAERESIS"); \
	genSvg(fontname, "0x03CC", "GREEK SMALL LETTER OMICRON WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x03CD", "GREEK SMALL LETTER UPSILON WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x03CE", "GREEK SMALL LETTER OMEGA WITH ACUTE ACCENT"); \
	genSvg(fontname, "0x03CF", "GREEK CAPITAL KAI SYMBOL"); \
	genSvg(fontname, "0x03D0", "GREEK BETA SYMBOL"); \
	genSvg(fontname, "0x03D1", "GREEK THETA SYMBOL"); \
	genSvg(fontname, "0x03D2", "GREEK UPSILON WITH HOOK SYMBOL"); \
	genSvg(fontname, "0x03D3", "GREEK UPSILON WITH ACUTE AND HOOK SYMBOL"); \
	genSvg(fontname, "0x03D4", "GREEK UPSILON WITH DIAERESIS AND HOOK SYMBOL"); \
	genSvg(fontname, "0x03D5", "GREEK PHI SYMBOL"); \
	genSvg(fontname, "0x03D6", "GREEK PI SYMBOL"); \
	genSvg(fontname, "0x03D7", "GREEK KAI SYMBOL"); \
	genSvg(fontname, "0x03D8", "GREEK LETTER QOPPA"); \
	genSvg(fontname, "0x03D9", "GREEK SMALL LETTER QOPPA"); \
	genSvg(fontname, "0x03DA", "GREEK LETTER STIGMA (LETTER)"); \
	genSvg(fontname, "0x03DB", "GREEK SMALL LETTER STIGMA"); \
	genSvg(fontname, "0x03DC", "GREEK LETTER DIGAMMA"); \
	genSvg(fontname, "0x03DD", "GREEK SMALL LETTER DIGAMMA"); \
	genSvg(fontname, "0x03DE", "GREEK LETTER KOPPA"); \
	genSvg(fontname, "0x03DF", "GREEK SMALL LETTER KOPPA"); \
	genSvg(fontname, "0x03E0", "GREEK LETTER SAMPI"); \
	genSvg(fontname, "0x03E1", "GREEK SMALL LETTER SAMPI"); \
	genSvg(fontname, "0x03E2", "COPTIC CAPITAL LETTER SHEI"); \
	genSvg(fontname, "0x03E3", "COPTIC SMALL LETTER SHEI"); \
	genSvg(fontname, "0x03E4", "COPTIC CAPITAL LETTER FEI"); \
	genSvg(fontname, "0x03E5", "COPTIC SMALL LETTER FEI"); \
	genSvg(fontname, "0x03E6", "COPTIC CAPITAL LETTER KHEI"); \
	genSvg(fontname, "0x03E7", "COPTIC SMALL LETTER KHEI"); \
	genSvg(fontname, "0x03E8", "COPTIC CAPITAL LETTER HORI"); \
	genSvg(fontname, "0x03E9", "COPTIC SMALL LETTER HORI"); \
	genSvg(fontname, "0x03EA", "COPTIC CAPITAL LETTER GANGIA"); \
	genSvg(fontname, "0x03EB", "COPTIC SMALL LETTER GANGIA"); \
	genSvg(fontname, "0x03EC", "COPTIC CAPITAL LETTER SHIMA"); \
	genSvg(fontname, "0x03ED", "COPTIC SMALL LETTER SHIMA"); \
	genSvg(fontname, "0x03EE", "COPTIC CAPITAL LETTER DEI"); \
	genSvg(fontname, "0x03EF", "COPTIC SMALL LETTER DEI"); \
	genSvg(fontname, "0x03F0", "GREEK KAPPA SYMBOL"); \
	genSvg(fontname, "0x03F1", "GREEK RHO SYMBOL"); \
	genSvg(fontname, "0x03F2", "GREEK LUNATE SIGMA SYMBOL"); \
	genSvg(fontname, "0x03F3", "GREEK LETTER YOT"); \
	genSvg(fontname, "0x03F4", "GREEK CAPITAL THETA SYMBOL"); \
	genSvg(fontname, "0x03F5", "GREEK LUNATE EPSILON SYMBOL"); \
	genSvg(fontname, "0x03F6", "GREEK REVERSED LUNATE EPSILON SYMBOL"); \
	genSvg(fontname, "0x03F7", "GREEK CAPITAL SHO"); \
	genSvg(fontname, "0x03F8", "GREEK SMALL LETTER SHO"); \
	genSvg(fontname, "0x03F9", "GREEK CAPITAL LUNATE SIGMA SYMBOL"); \
	genSvg(fontname, "0x03FA", "GREEK CAPITAL SAN"); \
	genSvg(fontname, "0x03FB", "GREEK SMALL LETTER SAN"); \
	genSvg(fontname, "0x03FC", "GREEK RHO WITH STROKE SYMBOL"); \
	genSvg(fontname, "0x03FD", "GREEK CAPITAL REVERSED LUNATE SIGMA SYMBOL"); \
	genSvg(fontname, "0x03FE", "GREEK CAPITAL DOTTED LUNATE SIGMA SYMBOL"); \
	genSvg(fontname, "0x03FF", "GREEK CAPITAL REVERSED DOTTED LUNATE SIGMA SYMBOL");

#define GREEK_EXTENDED \
	genSvg(fontname, "0x1F00", "GREEK SMALL LETTER ALPHA WITH PSILI"); \
	genSvg(fontname, "0x1F01", "GREEK SMALL LETTER ALPHA WITH DASIA"); \
	genSvg(fontname, "0x1F02", "GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F03", "GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F04", "GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F05", "GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F06", "GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1F07", "GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F08", "GREEK CAPITAL LETTER ALPHA WITH PSILI"); \
	genSvg(fontname, "0x1F09", "GREEK CAPITAL LETTER ALPHA WITH DASIA"); \
	genSvg(fontname, "0x1F0A", "GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F0B", "GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F0C", "GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F0D", "GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F0E", "GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1F0F", "GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F10", "GREEK SMALL LETTER EPSILON WITH PSILI"); \
	genSvg(fontname, "0x1F11", "GREEK SMALL LETTER EPSILON WITH DASIA"); \
	genSvg(fontname, "0x1F12", "GREEK SMALL LETTER EPSILON WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F13", "GREEK SMALL LETTER EPSILON WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F14", "GREEK SMALL LETTER EPSILON WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F15", "GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F18", "GREEK CAPITAL LETTER EPSILON WITH PSILI"); \
	genSvg(fontname, "0x1F19", "GREEK CAPITAL LETTER EPSILON WITH DASIA"); \
	genSvg(fontname, "0x1F1A", "GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F1B", "GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F1C", "GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F1D", "GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F20", "GREEK SMALL LETTER ETA WITH PSILI"); \
	genSvg(fontname, "0x1F21", "GREEK SMALL LETTER ETA WITH DASIA"); \
	genSvg(fontname, "0x1F22", "GREEK SMALL LETTER ETA WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F23", "GREEK SMALL LETTER ETA WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F24", "GREEK SMALL LETTER ETA WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F25", "GREEK SMALL LETTER ETA WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F26", "GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1F27", "GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F28", "GREEK CAPITAL LETTER ETA WITH PSILI"); \
	genSvg(fontname, "0x1F29", "GREEK CAPITAL LETTER ETA WITH DASIA"); \
	genSvg(fontname, "0x1F2A", "GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F2B", "GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F2C", "GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F2D", "GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F2E", "GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1F2F", "GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F30", "GREEK SMALL LETTER IOTA WITH PSILI"); \
	genSvg(fontname, "0x1F31", "GREEK SMALL LETTER IOTA WITH DASIA"); \
	genSvg(fontname, "0x1F32", "GREEK SMALL LETTER IOTA WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F33", "GREEK SMALL LETTER IOTA WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F34", "GREEK SMALL LETTER IOTA WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F35", "GREEK SMALL LETTER IOTA WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F36", "GREEK SMALL LETTER IOTA WITH PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1F37", "GREEK SMALL LETTER IOTA WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F38", "GREEK CAPITAL LETTER IOTA WITH PSILI"); \
	genSvg(fontname, "0x1F39", "GREEK CAPITAL LETTER IOTA WITH DASIA"); \
	genSvg(fontname, "0x1F3A", "GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F3B", "GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F3C", "GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F3D", "GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F3E", "GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1F3F", "GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F40", "GREEK SMALL LETTER OMICRON WITH PSILI"); \
	genSvg(fontname, "0x1F41", "GREEK SMALL LETTER OMICRON WITH DASIA"); \
	genSvg(fontname, "0x1F42", "GREEK SMALL LETTER OMICRON WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F43", "GREEK SMALL LETTER OMICRON WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F44", "GREEK SMALL LETTER OMICRON WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F45", "GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F48", "GREEK CAPITAL LETTER OMICRON WITH PSILI"); \
	genSvg(fontname, "0x1F49", "GREEK CAPITAL LETTER OMICRON WITH DASIA"); \
	genSvg(fontname, "0x1F4A", "GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F4B", "GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F4C", "GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F4D", "GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F50", "GREEK SMALL LETTER UPSILON WITH PSILI"); \
	genSvg(fontname, "0x1F51", "GREEK SMALL LETTER UPSILON WITH DASIA"); \
	genSvg(fontname, "0x1F52", "GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F53", "GREEK SMALL LETTER UPSILON WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F54", "GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F55", "GREEK SMALL LETTER UPSILON WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F56", "GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1F57", "GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F59", "GREEK CAPITAL LETTER UPSILON WITH DASIA"); \
	genSvg(fontname, "0x1F5B", "GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F5D", "GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F5F", "GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F60", "GREEK SMALL LETTER OMEGA WITH PSILI"); \
	genSvg(fontname, "0x1F61", "GREEK SMALL LETTER OMEGA WITH DASIA"); \
	genSvg(fontname, "0x1F62", "GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F63", "GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F64", "GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F65", "GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F66", "GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1F67", "GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F68", "GREEK CAPITAL LETTER OMEGA WITH PSILI"); \
	genSvg(fontname, "0x1F69", "GREEK CAPITAL LETTER OMEGA WITH DASIA"); \
	genSvg(fontname, "0x1F6A", "GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA"); \
	genSvg(fontname, "0x1F6B", "GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA"); \
	genSvg(fontname, "0x1F6C", "GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA"); \
	genSvg(fontname, "0x1F6D", "GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA"); \
	genSvg(fontname, "0x1F6E", "GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1F6F", "GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1F70", "GREEK SMALL LETTER ALPHA WITH VARIA"); \
	genSvg(fontname, "0x1F71", "GREEK SMALL LETTER ALPHA WITH OXIA"); \
	genSvg(fontname, "0x1F72", "GREEK SMALL LETTER EPSILON WITH VARIA"); \
	genSvg(fontname, "0x1F73", "GREEK SMALL LETTER EPSILON WITH OXIA"); \
	genSvg(fontname, "0x1F74", "GREEK SMALL LETTER ETA WITH VARIA"); \
	genSvg(fontname, "0x1F75", "GREEK SMALL LETTER ETA WITH OXIA"); \
	genSvg(fontname, "0x1F76", "GREEK SMALL LETTER IOTA WITH VARIA"); \
	genSvg(fontname, "0x1F77", "GREEK SMALL LETTER IOTA WITH OXIA"); \
	genSvg(fontname, "0x1F78", "GREEK SMALL LETTER OMICRON WITH VARIA"); \
	genSvg(fontname, "0x1F79", "GREEK SMALL LETTER OMICRON WITH OXIA"); \
	genSvg(fontname, "0x1F7A", "GREEK SMALL LETTER UPSILON WITH VARIA"); \
	genSvg(fontname, "0x1F7B", "GREEK SMALL LETTER UPSILON WITH OXIA"); \
	genSvg(fontname, "0x1F7C", "GREEK SMALL LETTER OMEGA WITH VARIA"); \
	genSvg(fontname, "0x1F7D", "GREEK SMALL LETTER OMEGA WITH OXIA"); \
	genSvg(fontname, "0x1F80", "GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F81", "GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F82", "GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F83", "GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F84", "GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F85", "GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F86", "GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F87", "GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F88", "GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F89", "GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F8A", "GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F8B", "GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F8C", "GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F8D", "GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F8E", "GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F8F", "GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F90", "GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F91", "GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F92", "GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F93", "GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F94", "GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F95", "GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F96", "GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F97", "GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1F98", "GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F99", "GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F9A", "GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F9B", "GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F9C", "GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F9D", "GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F9E", "GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1F9F", "GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FA0", "GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FA1", "GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FA2", "GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FA3", "GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FA4", "GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FA5", "GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FA6", "GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FA7", "GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FA8", "GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FA9", "GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FAA", "GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FAB", "GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FAC", "GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FAD", "GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FAE", "GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FAF", "GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FB0", "GREEK SMALL LETTER ALPHA WITH VRACHY"); \
	genSvg(fontname, "0x1FB1", "GREEK SMALL LETTER ALPHA WITH MACRON"); \
	genSvg(fontname, "0x1FB2", "GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FB3", "GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FB4", "GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FB6", "GREEK SMALL LETTER ALPHA WITH PERISPOMENI"); \
	genSvg(fontname, "0x1FB7", "GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FB8", "GREEK CAPITAL LETTER ALPHA WITH VRACHY"); \
	genSvg(fontname, "0x1FB9", "GREEK CAPITAL LETTER ALPHA WITH MACRON"); \
	genSvg(fontname, "0x1FBA", "GREEK CAPITAL LETTER ALPHA WITH VARIA"); \
	genSvg(fontname, "0x1FBB", "GREEK CAPITAL LETTER ALPHA WITH OXIA"); \
	genSvg(fontname, "0x1FBC", "GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FBD", "GREEK KORONIS"); \
	genSvg(fontname, "0x1FBE", "GREEK PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FBF", "GREEK PSILI"); \
	genSvg(fontname, "0x1FC0", "GREEK PERISPOMENI"); \
	genSvg(fontname, "0x1FC1", "GREEK DIALYTIKA AND PERISPOMENI"); \
	genSvg(fontname, "0x1FC2", "GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FC3", "GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FC4", "GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FC6", "GREEK SMALL LETTER ETA WITH PERISPOMENI"); \
	genSvg(fontname, "0x1FC7", "GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FC8", "GREEK CAPITAL LETTER EPSILON WITH VARIA"); \
	genSvg(fontname, "0x1FC9", "GREEK CAPITAL LETTER EPSILON WITH OXIA"); \
	genSvg(fontname, "0x1FCA", "GREEK CAPITAL LETTER ETA WITH VARIA"); \
	genSvg(fontname, "0x1FCB", "GREEK CAPITAL LETTER ETA WITH OXIA"); \
	genSvg(fontname, "0x1FCC", "GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FCD", "GREEK PSILI AND VARIA"); \
	genSvg(fontname, "0x1FCE", "GREEK PSILI AND OXIA"); \
	genSvg(fontname, "0x1FCF", "GREEK PSILI AND PERISPOMENI"); \
	genSvg(fontname, "0x1FD0", "GREEK SMALL LETTER IOTA WITH VRACHY"); \
	genSvg(fontname, "0x1FD1", "GREEK SMALL LETTER IOTA WITH MACRON"); \
	genSvg(fontname, "0x1FD2", "GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA"); \
	genSvg(fontname, "0x1FD3", "GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA"); \
	genSvg(fontname, "0x1FD6", "GREEK SMALL LETTER IOTA WITH PERISPOMENI"); \
	genSvg(fontname, "0x1FD7", "GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI"); \
	genSvg(fontname, "0x1FD8", "GREEK CAPITAL LETTER IOTA WITH VRACHY"); \
	genSvg(fontname, "0x1FD9", "GREEK CAPITAL LETTER IOTA WITH MACRON"); \
	genSvg(fontname, "0x1FDA", "GREEK CAPITAL LETTER IOTA WITH VARIA"); \
	genSvg(fontname, "0x1FDB", "GREEK CAPITAL LETTER IOTA WITH OXIA"); \
	genSvg(fontname, "0x1FDD", "GREEK DASIA AND VARIA"); \
	genSvg(fontname, "0x1FDE", "GREEK DASIA AND OXIA"); \
	genSvg(fontname, "0x1FDF", "GREEK DASIA AND PERISPOMENI"); \
	genSvg(fontname, "0x1FE0", "GREEK SMALL LETTER UPSILON WITH VRACHY"); \
	genSvg(fontname, "0x1FE1", "GREEK SMALL LETTER UPSILON WITH MACRON"); \
	genSvg(fontname, "0x1FE2", "GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA"); \
	genSvg(fontname, "0x1FE3", "GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA"); \
	genSvg(fontname, "0x1FE4", "GREEK SMALL LETTER RHO WITH PSILI"); \
	genSvg(fontname, "0x1FE5", "GREEK SMALL LETTER RHO WITH DASIA"); \
	genSvg(fontname, "0x1FE6", "GREEK SMALL LETTER UPSILON WITH PERISPOMENI"); \
	genSvg(fontname, "0x1FE7", "GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI"); \
	genSvg(fontname, "0x1FE8", "GREEK CAPITAL LETTER UPSILON WITH VRACHY"); \
	genSvg(fontname, "0x1FE9", "GREEK CAPITAL LETTER UPSILON WITH MACRON"); \
	genSvg(fontname, "0x1FEA", "GREEK CAPITAL LETTER UPSILON WITH VARIA"); \
	genSvg(fontname, "0x1FEB", "GREEK CAPITAL LETTER UPSILON WITH OXIA"); \
	genSvg(fontname, "0x1FEC", "GREEK CAPITAL LETTER RHO WITH DASIA"); \
	genSvg(fontname, "0x1FED", "GREEK DIALYTIKA AND VARIA"); \
	genSvg(fontname, "0x1FEE", "GREEK DIALYTIKA AND OXIA"); \
	genSvg(fontname, "0x1FEF", "GREEK VARIA"); \
	genSvg(fontname, "0x1FF2", "GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FF3", "GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FF4", "GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FF6", "GREEK SMALL LETTER OMEGA WITH PERISPOMENI"); \
	genSvg(fontname, "0x1FF7", "GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI"); \
	genSvg(fontname, "0x1FF8", "GREEK CAPITAL LETTER OMICRON WITH VARIA"); \
	genSvg(fontname, "0x1FF9", "GREEK CAPITAL LETTER OMICRON WITH OXIA"); \
	genSvg(fontname, "0x1FFA", "GREEK CAPITAL LETTER OMEGA WITH VARIA"); \
	genSvg(fontname, "0x1FFB", "GREEK CAPITAL LETTER OMEGA WITH OXIA"); \
	genSvg(fontname, "0x1FFC", "GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI"); \
	genSvg(fontname, "0x1FFD", "GREEK OXIA"); \
	genSvg(fontname, "0x1FFE", "GREEK DASIA");