//
// main.cpp - font_to_svg
// Vinyl Darkscratch © 2018, MIT License.
// www.queengoob.org
// 
// This program takes a given TTF font file and generates SVGs for every available glyph.  Currently supports:
// - Basic Latin
// - Latin-1 Supplement
// - Latin Extended-A
// - Latin Extended-B
// - Latin Extended Additional
// - IPA Extensions
// - Spacing Modifier Letters
// - Greek and Coptic
// - Cyrillic
// - Unicode Symbols
// - Block Elements
// - Geometric Shapes
//

// TODO: Add more characters as listed on https://en.wikipedia.org/wiki/List_of_Unicode_characters

#include <iostream>
#include <fstream>
#include "font_to_svg.hpp"

void genSvg(std::string fontname, std::string charCode, std::string name) {
	// Obtain the given glyph
	font2svg::glyph g(fontname.c_str(), charCode);
	std::string data = g.outline();

	if (data != "<!-- font had 0 points -->" && data != "<!-- font had 0 contours -->") { // Create the file if the glyph exists
		std::string fname = std::string("./Output/") + charCode + " - " + name + ".svg";
		std::ofstream file(fname.c_str());
		file << g.svgheader() << g.svgtransform() << g.svgborder() << data << g.svgfooter();
		file.close();
	}

	g.free();
}

void create_svgs(std::string fontname) {
	// -=- Basic Latin

	// ASCII Punctuation & Symbols
	genSvg(fontname, "0x0021", "EXCLAMATION MARK");
	genSvg(fontname, "0x0022", "QUOTATION MARK");
	genSvg(fontname, "0x0023", "NUMBER SIGN");
	genSvg(fontname, "0x0024", "DOLLAR SIGN");
	genSvg(fontname, "0x0025", "PERCENT SIGN");
	genSvg(fontname, "0x0026", "AMPERSAND");
	genSvg(fontname, "0x0027", "APOSTROPHE");
	genSvg(fontname, "0x0028", "LEFT PARENTHESIS");
	genSvg(fontname, "0x0029", "RIGHT PARENTHESIS");
	genSvg(fontname, "0x002A", "ASTERISK");
	genSvg(fontname, "0x002B", "PLUS SIGN");
	genSvg(fontname, "0x002C", "COMMA");
	genSvg(fontname, "0x002D", "HYPHEN-MINUS");
	genSvg(fontname, "0x002E", "FULL STOP");
	genSvg(fontname, "0x002F", "FORWARD SLASH");

	// ASCII Digits
	genSvg(fontname, "0x0030", "DIGIT ZERO");
	genSvg(fontname, "0x0031", "DIGIT ONE");
	genSvg(fontname, "0x0032", "DIGIT TWO");
	genSvg(fontname, "0x0033", "DIGIT THREE");
	genSvg(fontname, "0x0034", "DIGIT FOUR");
	genSvg(fontname, "0x0035", "DIGIT FIVE");
	genSvg(fontname, "0x0036", "DIGIT SIX");
	genSvg(fontname, "0x0037", "DIGIT SEVEN");
	genSvg(fontname, "0x0038", "DIGIT EIGHT");
	genSvg(fontname, "0x0039", "DIGIT NINE");

	// ASCII Punctuation & Symbols
	genSvg(fontname, "0x003A", "COLON");
	genSvg(fontname, "0x003B", "SEMICOLON");
	genSvg(fontname, "0x003C", "LESS-THAN SIGN");
	genSvg(fontname, "0x003D", "EQUAL SIGN");
	genSvg(fontname, "0x003E", "GREATER-THAN SIGN");
	genSvg(fontname, "0x003F", "QUESTION MARK");
	genSvg(fontname, "0x0040", "AT SIGN");

	// Latin Alphabet: Uppercase
	genSvg(fontname, "0x0041", "LATIN CAPITAL LETTER A");
	genSvg(fontname, "0x0042", "LATIN CAPITAL LETTER B");
	genSvg(fontname, "0x0043", "LATIN CAPITAL LETTER C");
	genSvg(fontname, "0x0044", "LATIN CAPITAL LETTER D");
	genSvg(fontname, "0x0045", "LATIN CAPITAL LETTER E");
	genSvg(fontname, "0x0046", "LATIN CAPITAL LETTER F");
	genSvg(fontname, "0x0047", "LATIN CAPITAL LETTER G");
	genSvg(fontname, "0x0048", "LATIN CAPITAL LETTER H");
	genSvg(fontname, "0x0049", "LATIN CAPITAL LETTER I");
	genSvg(fontname, "0x004A", "LATIN CAPITAL LETTER J");
	genSvg(fontname, "0x004B", "LATIN CAPITAL LETTER K");
	genSvg(fontname, "0x004C", "LATIN CAPITAL LETTER L");
	genSvg(fontname, "0x004D", "LATIN CAPITAL LETTER M");
	genSvg(fontname, "0x004E", "LATIN CAPITAL LETTER N");
	genSvg(fontname, "0x004F", "LATIN CAPITAL LETTER O");
	genSvg(fontname, "0x0050", "LATIN CAPITAL LETTER P");
	genSvg(fontname, "0x0051", "LATIN CAPITAL LETTER Q");
	genSvg(fontname, "0x0052", "LATIN CAPITAL LETTER R");
	genSvg(fontname, "0x0053", "LATIN CAPITAL LETTER S");
	genSvg(fontname, "0x0054", "LATIN CAPITAL LETTER T");
	genSvg(fontname, "0x0055", "LATIN CAPITAL LETTER U");
	genSvg(fontname, "0x0056", "LATIN CAPITAL LETTER V");
	genSvg(fontname, "0x0057", "LATIN CAPITAL LETTER W");
	genSvg(fontname, "0x0058", "LATIN CAPITAL LETTER X");
	genSvg(fontname, "0x0059", "LATIN CAPITAL LETTER Y");
	genSvg(fontname, "0x005A", "LATIN CAPITAL LETTER Z");

	// ASCII Punctuation & Symbols
	genSvg(fontname, "0x005B", "LEFT SQUARE BRACKET");
	genSvg(fontname, "0x005C", "BACKSLASH");
	genSvg(fontname, "0x005D", "RIGHT SQUARE BRACKET");
	genSvg(fontname, "0x005E", "CIRCUMFLEX ACCENT");
	genSvg(fontname, "0x005F", "LOW LINE");
	genSvg(fontname, "0x0060", "GRAVE ACCENT");

	// Latin Alphabet: Lowercase
	genSvg(fontname, "0x0061", "LATIN SMALL LETTER A");
	genSvg(fontname, "0x0062", "LATIN SMALL LETTER B");
	genSvg(fontname, "0x0063", "LATIN SMALL LETTER C");
	genSvg(fontname, "0x0064", "LATIN SMALL LETTER D");
	genSvg(fontname, "0x0065", "LATIN SMALL LETTER E");
	genSvg(fontname, "0x0066", "LATIN SMALL LETTER F");
	genSvg(fontname, "0x0067", "LATIN SMALL LETTER G");
	genSvg(fontname, "0x0068", "LATIN SMALL LETTER H");
	genSvg(fontname, "0x0069", "LATIN SMALL LETTER I");
	genSvg(fontname, "0x006A", "LATIN SMALL LETTER J");
	genSvg(fontname, "0x006B", "LATIN SMALL LETTER K");
	genSvg(fontname, "0x006C", "LATIN SMALL LETTER L");
	genSvg(fontname, "0x006D", "LATIN SMALL LETTER M");
	genSvg(fontname, "0x006E", "LATIN SMALL LETTER N");
	genSvg(fontname, "0x006F", "LATIN SMALL LETTER O");
	genSvg(fontname, "0x0070", "LATIN SMALL LETTER P");
	genSvg(fontname, "0x0071", "LATIN SMALL LETTER Q");
	genSvg(fontname, "0x0072", "LATIN SMALL LETTER R");
	genSvg(fontname, "0x0073", "LATIN SMALL LETTER S");
	genSvg(fontname, "0x0074", "LATIN SMALL LETTER T");
	genSvg(fontname, "0x0075", "LATIN SMALL LETTER U");
	genSvg(fontname, "0x0076", "LATIN SMALL LETTER V");
	genSvg(fontname, "0x0077", "LATIN SMALL LETTER W");
	genSvg(fontname, "0x0078", "LATIN SMALL LETTER X");
	genSvg(fontname, "0x0079", "LATIN SMALL LETTER Y");
	genSvg(fontname, "0x007A", "LATIN SMALL LETTER Z");

	// ASCII Punctuation & Symbols
	genSvg(fontname, "0x007B", "LEFT CURLY BRACKET");
	genSvg(fontname, "0x007C", "VERTICAL BAR");
	genSvg(fontname, "0x007D", "RIGHT CURLY BRACKET");
	genSvg(fontname, "0x007E", "TILDE");

	// -=- Latin-1 Supplement

	// Latin-1 Punctuation & Symbols
	genSvg(fontname, "0x00A1", "INVERTED EXCLAMATION MARK");
	genSvg(fontname, "0x00A2", "CENT SIGN");
	genSvg(fontname, "0x00A3", "POUND SIGN");
	genSvg(fontname, "0x00A4", "CURRENCY SIGN");
	genSvg(fontname, "0x00A5", "YEN SIGN");
	genSvg(fontname, "0x00A6", "BROKEN BAR");
	genSvg(fontname, "0x00A7", "SECTION SIGN");
	genSvg(fontname, "0x00A8", "DIAERESIS");
	genSvg(fontname, "0x00A9", "COPYRIGHT SIGN");
	genSvg(fontname, "0x00AA", "FEMININE ORDINAL INDICATOR");
	genSvg(fontname, "0x00AB", "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK");
	genSvg(fontname, "0x00AC", "NOT SIGN");
	genSvg(fontname, "0x00AD", "SOFT HYPHEN");
	genSvg(fontname, "0x00AE", "REGISTERED SIGN");
	genSvg(fontname, "0x00AF", "MACRON");
	genSvg(fontname, "0x00B0", "DEGREE SYMBOL");
	genSvg(fontname, "0x00B1", "PLUS-MINUS SIGN");
	genSvg(fontname, "0x00B2", "SUPERSCRIPT TWO");
	genSvg(fontname, "0x00B3", "SUPERSCRIPT THREE");
	genSvg(fontname, "0x00B4", "ACUTE ACCENT");
	genSvg(fontname, "0x00B5", "MICRO SIGN");
	genSvg(fontname, "0x00B6", "PILCROW SIGN");
	genSvg(fontname, "0x00B7", "MIDDLE DOT");
	genSvg(fontname, "0x00B8", "CEDILLA");
	genSvg(fontname, "0x00B9", "SUPERSCRIPT ONE");
	genSvg(fontname, "0x00BA", "MASCULINE ORDINAL INDICATOR");
	genSvg(fontname, "0x00BB", "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK");
	genSvg(fontname, "0x00BC", "VULGAR FRACTION ONE QUARTER");
	genSvg(fontname, "0x00BD", "VULGAR FRACTION ONE HALF");
	genSvg(fontname, "0x00BE", "VULGAR FRACTION THREE QUARTERS");
	genSvg(fontname, "0x00BF", "INVERTED QUESTION MARK");

	// Letters: Uppercase
	genSvg(fontname, "0x00C0", "LATIN CAPITAL LETTER A WITH GRAVE");
	genSvg(fontname, "0x00C1", "LATIN CAPITAL LETTER A WITH ACUTE");
	genSvg(fontname, "0x00C2", "LATIN CAPITAL LETTER A WITH CIRCUMFLEX");
	genSvg(fontname, "0x00C3", "LATIN CAPITAL LETTER A WITH TILDE");
	genSvg(fontname, "0x00C4", "LATIN CAPITAL LETTER A WITH DIAERESIS");
	genSvg(fontname, "0x00C5", "LATIN CAPITAL LETTER A WITH RING ABOVE");
	genSvg(fontname, "0x00C6", "LATIN CAPITAL LETTER AE");
	genSvg(fontname, "0x00C7", "LATIN CAPITAL LETTER C WITH CEDILLA");
	genSvg(fontname, "0x00C8", "LATIN CAPITAL LETTER E WITH GRAVE");
	genSvg(fontname, "0x00C9", "LATIN CAPITAL LETTER E WITH ACUTE");
	genSvg(fontname, "0x00CA", "LATIN CAPITAL LETTER E WITH CIRCUMFLEX");
	genSvg(fontname, "0x00CB", "LATIN CAPITAL LETTER E WITH DIAERESIS");
	genSvg(fontname, "0x00CC", "LATIN CAPITAL LETTER I WITH GRAVE");
	genSvg(fontname, "0x00CD", "LATIN CAPITAL LETTER I WITH ACUTE");
	genSvg(fontname, "0x00CE", "LATIN CAPITAL LETTER I WITH CIRCUMFLEX");
	genSvg(fontname, "0x00CF", "LATIN CAPITAL LETTER I WITH DIAERESIS");
	genSvg(fontname, "0x00D0", "LATIN CAPITAL LETTER ETH");
	genSvg(fontname, "0x00D1", "LATIN CAPITAL LETTER N WITH TILDE");
	genSvg(fontname, "0x00D2", "LATIN CAPITAL LETTER O WITH GRAVE");
	genSvg(fontname, "0x00D3", "LATIN CAPITAL LETTER O WITH ACUTE");
	genSvg(fontname, "0x00D4", "LATIN CAPITAL LETTER O WITH CIRCUMFLEX");
	genSvg(fontname, "0x00D5", "LATIN CAPITAL LETTER O WITH TILDE");
	genSvg(fontname, "0x00D6", "LATIN CAPITAL LETTER O WITH DIAERESIS");

	// Math
	genSvg(fontname, "0x00D7", "MULTIPLICATION SIGN");

	// Letters: Uppercase
	genSvg(fontname, "0x00D8", "LATIN CAPITAL LETTER O WITH STROKE");
	genSvg(fontname, "0x00D9", "LATIN CAPITAL LETTER U WITH GRAVE");
	genSvg(fontname, "0x00DA", "LATIN CAPITAL LETTER U WITH ACUTE");
	genSvg(fontname, "0x00DB", "LATIN CAPITAL LETTER U WITH CIRCUMFLEX");
	genSvg(fontname, "0x00DC", "LATIN CAPITAL LETTER U WITH DIAERESIS");
	genSvg(fontname, "0x00DD", "LATIN CAPITAL LETTER Y WITH ACUTE");
	genSvg(fontname, "0x00DE", "LATIN CAPITAL LETTER THORN");

	// Letters: Lowercase
	genSvg(fontname, "0x00DF", "LATIN SMALL LETTER SHARP S");
	genSvg(fontname, "0x00E0", "LATIN SMALL LETTER A WITH GRAVE");
	genSvg(fontname, "0x00E1", "LATIN SMALL LETTER A WITH ACUTE");
	genSvg(fontname, "0x00E2", "LATIN SMALL LETTER A WITH CIRCUMFLEX");
	genSvg(fontname, "0x00E3", "LATIN SMALL LETTER A WITH TILDE");
	genSvg(fontname, "0x00E4", "LATIN SMALL LETTER A WITH DIAERESIS");
	genSvg(fontname, "0x00E5", "LATIN SMALL LETTER A WITH RING ABOVE");
	genSvg(fontname, "0x00E6", "LATIN SMALL LETTER AE");
	genSvg(fontname, "0x00E7", "LATIN SMALL LETTER C WITH CEDILLA");
	genSvg(fontname, "0x00E8", "LATIN SMALL LETTER E WITH GRAVE");
	genSvg(fontname, "0x00E9", "LATIN SMALL LETTER E WITH ACUTE");
	genSvg(fontname, "0x00EA", "LATIN SMALL LETTER E WITH CIRCUMFLEX");
	genSvg(fontname, "0x00EB", "LATIN SMALL LETTER E WITH DIAERESIS");
	genSvg(fontname, "0x00EC", "LATIN SMALL LETTER I WITH GRAVE");
	genSvg(fontname, "0x00ED", "LATIN SMALL LETTER I WITH ACUTE");
	genSvg(fontname, "0x00EE", "LATIN SMALL LETTER I WITH CIRCUMFLEX");
	genSvg(fontname, "0x00EF", "LATIN SMALL LETTER I WITH DIAERESIS");
	genSvg(fontname, "0x00F0", "LATIN SMALL LETTER ETH");
	genSvg(fontname, "0x00F1", "LATIN SMALL LETTER N WITH TILDE");
	genSvg(fontname, "0x00F2", "LATIN SMALL LETTER O WITH GRAVE");
	genSvg(fontname, "0x00F3", "LATIN SMALL LETTER O WITH ACUTE");
	genSvg(fontname, "0x00F4", "LATIN SMALL LETTER O WITH CIRCUMFLEX");
	genSvg(fontname, "0x00F5", "LATIN SMALL LETTER O WITH TILDE");
	genSvg(fontname, "0x00F6", "LATIN SMALL LETTER O WITH DIAERESIS");

	// Math
	genSvg(fontname, "0x00F7", "DIVISION SIGN");

	// Letters: Lowercase
	genSvg(fontname, "0x00F8", "LATIN SMALL LETTER O WITH STROKE");
	genSvg(fontname, "0x00F9", "LATIN SMALL LETTER U WITH GRAVE");
	genSvg(fontname, "0x00FA", "LATIN SMALL LETTER U WITH ACUTE");
	genSvg(fontname, "0x00FB", "LATIN SMALL LETTER U WITH CIRCUMFLEX");
	genSvg(fontname, "0x00FC", "LATIN SMALL LETTER U WITH DIAERESIS");
	genSvg(fontname, "0x00FD", "LATIN SMALL LETTER Y WITH ACUTE");
	genSvg(fontname, "0x00FE", "LATIN SMALL LETTER THORN");
	genSvg(fontname, "0x00FF", "LATIN SMALL LETTER Y WITH DIAERESIS");

	// -=- Latin Extended-A

	genSvg(fontname, "0x0100", "LATIN CAPITAL LETTER A WITH MACRON");
	genSvg(fontname, "0x0101", "LATIN SMALL LETTER A WITH MACRON");
	genSvg(fontname, "0x0102", "LATIN CAPITAL LETTER A WITH BREVE");
	genSvg(fontname, "0x0103", "LATIN SMALL LETTER A WITH BREVE");
	genSvg(fontname, "0x0104", "LATIN CAPITAL LETTER A WITH OGONEK");
	genSvg(fontname, "0x0105", "LATIN SMALL LETTER A WITH OGONEK");
	genSvg(fontname, "0x0106", "LATIN CAPITAL LETTER C WITH ACUTE");
	genSvg(fontname, "0x0107", "LATIN SMALL LETTER C WITH ACUTE");
	genSvg(fontname, "0x0108", "LATIN CAPITAL LETTER C WITH CIRCUMFLEX");
	genSvg(fontname, "0x0109", "LATIN SMALL LETTER C WITH CIRCUMFLEX");
	genSvg(fontname, "0x010A", "LATIN CAPITAL LETTER C WITH DOT ABOVE");
	genSvg(fontname, "0x010B", "LATIN SMALL LETTER C WITH DOT ABOVE");
	genSvg(fontname, "0x010C", "LATIN CAPITAL LETTER C WITH CARON");
	genSvg(fontname, "0x010D", "LATIN SMALL LETTER C WITH CARON");
	genSvg(fontname, "0x010E", "LATIN CAPITAL LETTER D WITH CARON");
	genSvg(fontname, "0x010F", "LATIN SMALL LETTER D WITH CARON");
	genSvg(fontname, "0x0110", "LATIN CAPITAL LETTER D WITH STROKE");
	genSvg(fontname, "0x0111", "LATIN SMALL LETTER D WITH STROKE");
	genSvg(fontname, "0x0112", "LATIN CAPITAL LETTER E WITH MACRON");
	genSvg(fontname, "0x0113", "LATIN SMALL LETTER E WITH MACRON");
	genSvg(fontname, "0x0114", "LATIN CAPITAL LETTER E WITH BREVE");
	genSvg(fontname, "0x0115", "LATIN SMALL LETTER E WITH BREVE");
	genSvg(fontname, "0x0116", "LATIN CAPITAL LETTER E WITH DOT ABOVE");
	genSvg(fontname, "0x0117", "LATIN SMALL LETTER E WITH DOT ABOVE");
	genSvg(fontname, "0x0118", "LATIN CAPITAL LETTER E WITH OGONEK");
	genSvg(fontname, "0x0119", "LATIN SMALL LETTER E WITH OGONEK");
	genSvg(fontname, "0x011A", "LATIN CAPITAL LETTER E WITH CARON");
	genSvg(fontname, "0x011B", "LATIN SMALL LETTER E WITH CARON");
	genSvg(fontname, "0x011C", "LATIN CAPITAL LETTER G WITH CIRCUMFLEX");
	genSvg(fontname, "0x011D", "LATIN SMALL LETTER G WITH CIRCUMFLEX");
	genSvg(fontname, "0x011E", "LATIN CAPITAL LETTER G WITH BREVE");
	genSvg(fontname, "0x011F", "LATIN SMALL LETTER G WITH BREVE");
	genSvg(fontname, "0x0120", "LATIN CAPITAL LETTER G WITH DOT ABOVE");
	genSvg(fontname, "0x0121", "LATIN SMALL LETTER G WITH DOT ABOVE");
	genSvg(fontname, "0x0122", "LATIN CAPITAL LETTER G WITH CEDILLA");
	genSvg(fontname, "0x0123", "LATIN SMALL LETTER G WITH CEDILLA");
	genSvg(fontname, "0x0124", "LATIN CAPITAL LETTER H WITH CIRCUMFLEX");
	genSvg(fontname, "0x0125", "LATIN SMALL LETTER H WITH CIRCUMFLEX");
	genSvg(fontname, "0x0126", "LATIN CAPITAL LETTER H WITH STROKE");
	genSvg(fontname, "0x0127", "LATIN SMALL LETTER H WITH STROKE");
	genSvg(fontname, "0x0128", "LATIN CAPITAL LETTER I WITH TILDE");
	genSvg(fontname, "0x0129", "LATIN SMALL LETTER I WITH TILDE");
	genSvg(fontname, "0x012A", "LATIN CAPITAL LETTER I WITH MACRON");
	genSvg(fontname, "0x012B", "LATIN SMALL LETTER I WITH MACRON");
	genSvg(fontname, "0x012C", "LATIN CAPITAL LETTER I WITH BREVE");
	genSvg(fontname, "0x012D", "LATIN SMALL LETTER I WITH BREVE");
	genSvg(fontname, "0x012E", "LATIN CAPITAL LETTER I WITH OGONEK");
	genSvg(fontname, "0x012F", "LATIN SMALL LETTER I WITH OGONEK");
	genSvg(fontname, "0x0130", "LATIN CAPITAL LETTER I WITH DOT ABOVE");
	genSvg(fontname, "0x0131", "LATIN SMALL LETTER DOTLESS I");
	genSvg(fontname, "0x0132", "LATIN CAPITAL LIGATURE IJ");
	genSvg(fontname, "0x0133", "LATIN SMALL LIGATURE IJ");
	genSvg(fontname, "0x0134", "LATIN CAPITAL LETTER J WITH CIRCUMFLEX");
	genSvg(fontname, "0x0135", "LATIN SMALL LETTER J WITH CIRCUMFLEX");
	genSvg(fontname, "0x0136", "LATIN CAPITAL LETTER K WITH CEDILLA");
	genSvg(fontname, "0x0137", "LATIN SMALL LETTER K WITH CEDILLA");
	genSvg(fontname, "0x0138", "LATIN SMALL LETTER KRA");
	genSvg(fontname, "0x0139", "LATIN CAPITAL LETTER L WITH ACUTE");
	genSvg(fontname, "0x013A", "LATIN SMALL LETTER L WITH ACUTE");
	genSvg(fontname, "0x013B", "LATIN CAPITAL LETTER L WITH CEDILLA");
	genSvg(fontname, "0x013C", "LATIN SMALL LETTER L WITH CEDILLA");
	genSvg(fontname, "0x013D", "LATIN CAPITAL LETTER L WITH CARON");
	genSvg(fontname, "0x013E", "LATIN SMALL LETTER L WITH CARON");
	genSvg(fontname, "0x013F", "LATIN CAPITAL LETTER L WITH MIDDLE DOT");
	genSvg(fontname, "0x0140", "LATIN SMALL LETTER L WITH MIDDLE DOT");
	genSvg(fontname, "0x0141", "LATIN CAPITAL LETTER L WITH STROKE");
	genSvg(fontname, "0x0142", "LATIN SMALL LETTER L WITH STROKE");
	genSvg(fontname, "0x0143", "LATIN CAPITAL LETTER N WITH ACUTE");
	genSvg(fontname, "0x0144", "LATIN SMALL LETTER N WITH ACUTE");
	genSvg(fontname, "0x0145", "LATIN CAPITAL LETTER N WITH CEDILLA");
	genSvg(fontname, "0x0146", "LATIN SMALL LETTER N WITH CEDILLA");
	genSvg(fontname, "0x0147", "LATIN CAPITAL LETTER N WITH CARON");
	genSvg(fontname, "0x0148", "LATIN SMALL LETTER N WITH CARON");
	genSvg(fontname, "0x014A", "LATIN CAPITAL LETTER ENG");
	genSvg(fontname, "0x014B", "LATIN SMALL LETTER ENG");
	genSvg(fontname, "0x014C", "LATIN CAPITAL LETTER O WITH MACRON");
	genSvg(fontname, "0x014D", "LATIN SMALL LETTER O WITH MACRON");
	genSvg(fontname, "0x014E", "LATIN CAPITAL LETTER O WITH BREVE");
	genSvg(fontname, "0x014F", "LATIN SMALL LETTER O WITH BREVE");
	genSvg(fontname, "0x0150", "LATIN CAPITAL LETTER O WITH DOUBLE ACUTE");
	genSvg(fontname, "0x0151", "LATIN SMALL LETTER O WITH DOUBLE ACUTE");
	genSvg(fontname, "0x0152", "LATIN CAPITAL LIGATURE OE");
	genSvg(fontname, "0x0153", "LATIN SMALL LIGATURE OE");
	genSvg(fontname, "0x0154", "LATIN CAPITAL LETTER R WITH ACUTE");
	genSvg(fontname, "0x0155", "LATIN SMALL LETTER R WITH ACUTE");
	genSvg(fontname, "0x0156", "LATIN CAPITAL LETTER R WITH CEDILLA");
	genSvg(fontname, "0x0157", "LATIN SMALL LETTER R WITH CEDILLA");
	genSvg(fontname, "0x0158", "LATIN CAPITAL LETTER R WITH CARON");
	genSvg(fontname, "0x0159", "LATIN SMALL LETTER R WITH CARON");
	genSvg(fontname, "0x015A", "LATIN CAPITAL LETTER S WITH ACUTE");
	genSvg(fontname, "0x015B", "LATIN SMALL LETTER S WITH ACUTE");
	genSvg(fontname, "0x015C", "LATIN CAPITAL LETTER S WITH CIRCUMFLEX");
	genSvg(fontname, "0x015D", "LATIN SMALL LETTER S WITH CIRCUMFLEX");
	genSvg(fontname, "0x015E", "LATIN CAPITAL LETTER S WITH CEDILLA");
	genSvg(fontname, "0x015F", "LATIN SMALL LETTER S WITH CEDILLA");
	genSvg(fontname, "0x0160", "LATIN CAPITAL LETTER S WITH CARON");
	genSvg(fontname, "0x0161", "LATIN SMALL LETTER S WITH CARON");
	genSvg(fontname, "0x0162", "LATIN CAPITAL LETTER T WITH CEDILLA");
	genSvg(fontname, "0x0163", "LATIN SMALL LETTER T WITH CEDILLA");
	genSvg(fontname, "0x0164", "LATIN CAPITAL LETTER T WITH CARON");
	genSvg(fontname, "0x0165", "LATIN SMALL LETTER T WITH CARON");
	genSvg(fontname, "0x0166", "LATIN CAPITAL LETTER T WITH STROKE");
	genSvg(fontname, "0x0167", "LATIN SMALL LETTER T WITH STROKE");
	genSvg(fontname, "0x0168", "LATIN CAPITAL LETTER U WITH TILDE");
	genSvg(fontname, "0x0169", "LATIN SMALL LETTER U WITH TILDE");
	genSvg(fontname, "0x016A", "LATIN CAPITAL LETTER U WITH MACRON");
	genSvg(fontname, "0x016B", "LATIN SMALL LETTER U WITH MACRON");
	genSvg(fontname, "0x016C", "LATIN CAPITAL LETTER U WITH BREVE");
	genSvg(fontname, "0x016D", "LATIN SMALL LETTER U WITH BREVE");
	genSvg(fontname, "0x016E", "LATIN CAPITAL LETTER U WITH RING ABOVE");
	genSvg(fontname, "0x016F", "LATIN SMALL LETTER U WITH RING ABOVE");
	genSvg(fontname, "0x0170", "LATIN CAPITAL LETTER U WITH DOUBLE ACUTE");
	genSvg(fontname, "0x0171", "LATIN SMALL LETTER U WITH DOUBLE ACUTE");
	genSvg(fontname, "0x0172", "LATIN CAPITAL LETTER U WITH OGONEK");
	genSvg(fontname, "0x0173", "LATIN SMALL LETTER U WITH OGONEK");
	genSvg(fontname, "0x0174", "LATIN CAPITAL LETTER W WITH CIRCUMFLEX");
	genSvg(fontname, "0x0175", "LATIN SMALL LETTER W WITH CIRCUMFLEX");
	genSvg(fontname, "0x0176", "LATIN CAPITAL LETTER Y WITH CIRCUMFLEX");
	genSvg(fontname, "0x0177", "LATIN SMALL LETTER Y WITH CIRCUMFLEX");
	genSvg(fontname, "0x0178", "LATIN CAPITAL LETTER Y WITH DIAERESIS");
	genSvg(fontname, "0x0179", "LATIN CAPITAL LETTER Z WITH ACUTE");
	genSvg(fontname, "0x017A", "LATIN SMALL LETTER Z WITH ACUTE");
	genSvg(fontname, "0x017B", "LATIN CAPITAL LETTER Z WITH DOT ABOVE");
	genSvg(fontname, "0x017C", "LATIN SMALL LETTER Z WITH DOT ABOVE");
	genSvg(fontname, "0x017D", "LATIN CAPITAL LETTER Z WITH CARON");
	genSvg(fontname, "0x017E", "LATIN SMALL LETTER Z WITH CARON");
	genSvg(fontname, "0x017F", "LATIN SMALL LETTER LONG S");

	// -=- Latin Extended-B

	// Non-European & Historic Latin
	genSvg(fontname, "0x0180", "LATIN SMALL LETTER B WITH STROKE");
	genSvg(fontname, "0x0181", "LATIN CAPITAL LETTER B WITH HOOK");
	genSvg(fontname, "0x0182", "LATIN CAPITAL LETTER B WITH TOP BAR");
	genSvg(fontname, "0x0183", "LATIN SMALL LETTER B WITH TOP BAR");
	genSvg(fontname, "0x0184", "LATIN CAPITAL LETTER TONE SIX");
	genSvg(fontname, "0x0185", "LATIN SMALL LETTER TONE SIX");
	genSvg(fontname, "0x0186", "LATIN CAPITAL LETTER OPEN O");
	genSvg(fontname, "0x0187", "LATIN CAPITAL LETTER C WITH HOOK");
	genSvg(fontname, "0x0188", "LATIN SMALL LETTER C WITH HOOK");
	genSvg(fontname, "0x0189", "LATIN CAPITAL LETTER AFRICAN D");
	genSvg(fontname, "0x018A", "LATIN CAPITAL LETTER D WITH HOOK");
	genSvg(fontname, "0x018B", "LATIN CAPITAL LETTER D WITH TOP BAR");
	genSvg(fontname, "0x018C", "LATIN SMALL LETTER D WITH TOP BAR");
	genSvg(fontname, "0x018D", "LATIN SMALL LETTER TURNED DELTA");
	genSvg(fontname, "0x018E", "LATIN CAPITAL LETTER REVERSED E");
	genSvg(fontname, "0x018F", "LATIN CAPITAL LETTER SCHWA");
	genSvg(fontname, "0x0190", "LATIN CAPITAL LETTER OPEN E");
	genSvg(fontname, "0x0191", "LATIN CAPITAL LETTER F WITH HOOK");
	genSvg(fontname, "0x0192", "LATIN SMALL LETTER F WITH HOOK");
	genSvg(fontname, "0x0193", "LATIN CAPITAL LETTER G WITH HOOK");
	genSvg(fontname, "0x0194", "LATIN CAPITAL LETTER GAMMA");
	genSvg(fontname, "0x0195", "LATIN SMALL LETTER HV");
	genSvg(fontname, "0x0196", "LATIN CAPITAL LETTER IOTA");
	genSvg(fontname, "0x0197", "LATIN CAPITAL LETTER I WITH STROKE");
	genSvg(fontname, "0x0198", "LATIN CAPITAL LETTER K WITH HOOK");
	genSvg(fontname, "0x0199", "LATIN SMALL LETTER K WITH HOOK");
	genSvg(fontname, "0x019A", "LATIN SMALL LETTER L WITH BAR");
	genSvg(fontname, "0x019B", "LATIN SMALL LETTER LAMBDA WITH STROKE");
	genSvg(fontname, "0x019C", "LATIN CAPITAL LETTER TURNED M");
	genSvg(fontname, "0x019D", "LATIN CAPITAL LETTER N WITH LEFT HOOK");
	genSvg(fontname, "0x019E", "LATIN SMALL LETTER N WITH LONG RIGHT LEG");
	genSvg(fontname, "0x019F", "LATIN CAPITAL LETTER O WITH MIDDLE TILDE");
	genSvg(fontname, "0x01A0", "LATIN CAPITAL LETTER O WITH HORN");
	genSvg(fontname, "0x01A1", "LATIN SMALL LETTER O WITH HORN");
	genSvg(fontname, "0x01A2", "LATIN CAPITAL LETTER OI");
	genSvg(fontname, "0x01A3", "LATIN SMALL LETTER OI");
	genSvg(fontname, "0x01A4", "LATIN CAPITAL LETTER P WITH HOOK");
	genSvg(fontname, "0x01A5", "LATIN SMALL LETTER P WITH HOOK");
	genSvg(fontname, "0x01A6", "LATIN LETTER YR");
	genSvg(fontname, "0x01A7", "LATIN CAPITAL LETTER TONE TWO");
	genSvg(fontname, "0x01A8", "LATIN SMALL LETTER TONE TWO");
	genSvg(fontname, "0x01A9", "LATIN CAPITAL LETTER ESH");
	genSvg(fontname, "0x01AA", "LATIN LETTER REVERSED ESH LOOP");
	genSvg(fontname, "0x01AB", "LATIN SMALL LETTER T WITH PALATAL HOOK");
	genSvg(fontname, "0x01AC", "LATIN CAPITAL LETTER T WITH HOOK");
	genSvg(fontname, "0x01AD", "LATIN SMALL LETTER T WITH HOOK");
	genSvg(fontname, "0x01AE", "LATIN CAPITAL LETTER T WITH RETROFLEX HOOK");
	genSvg(fontname, "0x01AF", "LATIN CAPITAL LETTER U WITH HORN");
	genSvg(fontname, "0x01B0", "LATIN SMALL LETTER U WITH HORN");
	genSvg(fontname, "0x01B1", "LATIN CAPITAL LETTER UPSILON");
	genSvg(fontname, "0x01B2", "LATIN CAPITAL LETTER V WITH HOOK");
	genSvg(fontname, "0x01B3", "LATIN CAPITAL LETTER Y WITH HOOK");
	genSvg(fontname, "0x01B4", "LATIN SMALL LETTER Y WITH HOOK");
	genSvg(fontname, "0x01B5", "LATIN CAPITAL LETTER Z WITH STROKE");
	genSvg(fontname, "0x01B6", "LATIN SMALL LETTER Z WITH STROKE");
	genSvg(fontname, "0x01B7", "LATIN CAPITAL LETTER EZH");
	genSvg(fontname, "0x01B8", "LATIN CAPITAL LETTER EZH REVERSED");
	genSvg(fontname, "0x01B9", "LATIN SMALL LETTER EZH REVERSED");
	genSvg(fontname, "0x01BA", "LATIN SMALL LETTER EZH WITH TAIL");
	genSvg(fontname, "0x01BB", "LATIN LETTER TWO WITH STROKE");
	genSvg(fontname, "0x01BC", "LATIN CAPITAL LETTER TONE FIVE");
	genSvg(fontname, "0x01BD", "LATIN SMALL LETTER TONE FIVE");
	genSvg(fontname, "0x01BE", "LATIN LETTER INVERTED GLOTTAL STOP WITH STROKE");
	genSvg(fontname, "0x01BF", "LATIN LETTER WYNN");

	// African Clicks
	genSvg(fontname, "0x01C0", "LATIN LETTER DENTAL CLICK");
	genSvg(fontname, "0x01C1", "LATIN LETTER LATERAL CLICK");
	genSvg(fontname, "0x01C2", "LATIN LETTER ALVEOLAR CLICK");
	genSvg(fontname, "0x01C3", "LATIN LETTER RETROFLEX CLICK");

	// Croatian
	genSvg(fontname, "0x01C4", "LATIN CAPITAL LETTER DZ WITH CARON");
	genSvg(fontname, "0x01C5", "LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON");
	genSvg(fontname, "0x01C6", "LATIN SMALL LETTER DZ WITH CARON");
	genSvg(fontname, "0x01C7", "LATIN CAPITAL LETTER LJ");
	genSvg(fontname, "0x01C8", "LATIN CAPITAL LETTER L WITH SMALL LETTER J");
	genSvg(fontname, "0x01C9", "LATIN SMALL LETTER LJ");
	genSvg(fontname, "0x01CA", "LATIN CAPITAL LETTER NJ");
	genSvg(fontname, "0x01CB", "LATIN CAPITAL LETTER N WITH SMALL LETTER J");
	genSvg(fontname, "0x01CC", "LATIN SMALL LETTER NJ");

	// Pinyin
	genSvg(fontname, "0x01CD", "LATIN CAPITAL LETTER A WITH CARON");
	genSvg(fontname, "0x01CE", "LATIN SMALL LETTER A WITH CARON");
	genSvg(fontname, "0x01CF", "LATIN CAPITAL LETTER I WITH CARON");
	genSvg(fontname, "0x01D0", "LATIN SMALL LETTER I WITH CARON");
	genSvg(fontname, "0x01D1", "LATIN CAPITAL LETTER O WITH CARON");
	genSvg(fontname, "0x01D2", "LATIN SMALL LETTER O WITH CARON");
	genSvg(fontname, "0x01D3", "LATIN CAPITAL LETTER U WITH CARON");
	genSvg(fontname, "0x01D4", "LATIN SMALL LETTER U WITH CARON");
	genSvg(fontname, "0x01D5", "LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON");
	genSvg(fontname, "0x01D6", "LATIN SMALL LETTER U WITH DIAERESIS AND MACRON");
	genSvg(fontname, "0x01D7", "LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE");
	genSvg(fontname, "0x01D8", "LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE");
	genSvg(fontname, "0x01D9", "LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON");
	genSvg(fontname, "0x01DA", "LATIN SMALL LETTER U WITH DIAERESIS AND CARON");
	genSvg(fontname, "0x01DB", "LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE");
	genSvg(fontname, "0x01DC", "LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE");

	// Phonetic & Historic Letters
	genSvg(fontname, "0x01DD", "LATIN SMALL LETTER TURNED E");
	genSvg(fontname, "0x01DE", "LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON");
	genSvg(fontname, "0x01DF", "LATIN SMALL LETTER A WITH DIAERESIS AND MACRON");
	genSvg(fontname, "0x01E0", "LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON");
	genSvg(fontname, "0x01E1", "LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON");
	genSvg(fontname, "0x01E2", "LATIN CAPITAL LETTER Æ WITH MACRON");
	genSvg(fontname, "0x01E3", "LATIN SMALL LETTER Æ WITH MACRON");
	genSvg(fontname, "0x01E4", "LATIN CAPITAL LETTER G WITH STROKE");
	genSvg(fontname, "0x01E5", "LATIN SMALL LETTER G WITH STROKE");
	genSvg(fontname, "0x01E6", "LATIN CAPITAL LETTER G WITH CARON");
	genSvg(fontname, "0x01E7", "LATIN SMALL LETTER G WITH CARON");
	genSvg(fontname, "0x01E8", "LATIN CAPITAL LETTER K WITH CARON");
	genSvg(fontname, "0x01E9", "LATIN SMALL LETTER K WITH CARON");
	genSvg(fontname, "0x01EA", "LATIN CAPITAL LETTER O WITH OGONEK");
	genSvg(fontname, "0x01EB", "LATIN SMALL LETTER O WITH OGONEK");
	genSvg(fontname, "0x01EC", "LATIN CAPITAL LETTER O WITH OGONEK AND MACRON");
	genSvg(fontname, "0x01ED", "LATIN SMALL LETTER O WITH OGONEK AND MACRON");
	genSvg(fontname, "0x01EE", "LATIN CAPITAL LETTER EZH WITH CARON");
	genSvg(fontname, "0x01EF", "LATIN SMALL LETTER EZH WITH CARON");
	genSvg(fontname, "0x01F0", "LATIN SMALL LETTER J WITH CARON");
	genSvg(fontname, "0x01F1", "LATIN CAPITAL LETTER DZ");
	genSvg(fontname, "0x01F2", "LATIN CAPITAL LETTER D WITH SMALL LETTER Z");
	genSvg(fontname, "0x01F3", "LATIN SMALL LETTER DZ");
	genSvg(fontname, "0x01F4", "LATIN CAPITAL LETTER G WITH ACUTE");
	genSvg(fontname, "0x01F5", "LATIN SMALL LETTER G WITH ACUTE");
	genSvg(fontname, "0x01F6", "LATIN CAPITAL LETTER HWAIR");
	genSvg(fontname, "0x01F7", "LATIN CAPITAL LETTER WYNN");
	genSvg(fontname, "0x01F8", "LATIN CAPITAL LETTER N WITH GRAVE");
	genSvg(fontname, "0x01F9", "LATIN SMALL LETTER N WITH GRAVE");
	genSvg(fontname, "0x01FA", "LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE");
	genSvg(fontname, "0x01FB", "LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE");
	genSvg(fontname, "0x01FC", "LATIN CAPITAL LETTER Æ WITH ACUTE");
	genSvg(fontname, "0x01FD", "LATIN SMALL LETTER Æ WITH ACUTE");
	genSvg(fontname, "0x01FE", "LATIN CAPITAL LETTER O WITH STROKE AND ACUTE");
	genSvg(fontname, "0x01FF", "LATIN SMALL LETTER O WITH STROKE AND ACUTE");

	// Slovenian & Croatian
	genSvg(fontname, "0x0200", "LATIN CAPITAL LETTER A WITH DOUBLE GRAVE");
	genSvg(fontname, "0x0201", "LATIN SMALL LETTER A WITH DOUBLE GRAVE");
	genSvg(fontname, "0x0202", "LATIN CAPITAL LETTER A WITH INVERTED BREVE");
	genSvg(fontname, "0x0203", "LATIN SMALL LETTER A WITH INVERTED BREVE");
	genSvg(fontname, "0x0204", "LATIN CAPITAL LETTER E WITH DOUBLE GRAVE");
	genSvg(fontname, "0x0205", "LATIN SMALL LETTER E WITH DOUBLE GRAVE");
	genSvg(fontname, "0x0206", "LATIN CAPITAL LETTER E WITH INVERTED BREVE");
	genSvg(fontname, "0x0207", "LATIN SMALL LETTER E WITH INVERTED BREVE");
	genSvg(fontname, "0x0208", "LATIN CAPITAL LETTER I WITH DOUBLE GRAVE");
	genSvg(fontname, "0x0209", "LATIN SMALL LETTER I WITH DOUBLE GRAVE");
	genSvg(fontname, "0x020A", "LATIN CAPITAL LETTER I WITH INVERTED BREVE");
	genSvg(fontname, "0x020B", "LATIN SMALL LETTER I WITH INVERTED BREVE");
	genSvg(fontname, "0x020C", "LATIN CAPITAL LETTER O WITH DOUBLE GRAVE");
	genSvg(fontname, "0x020D", "LATIN SMALL LETTER O WITH DOUBLE GRAVE");
	genSvg(fontname, "0x020E", "LATIN CAPITAL LETTER O WITH INVERTED BREVE");
	genSvg(fontname, "0x020F", "LATIN SMALL LETTER O WITH INVERTED BREVE");
	genSvg(fontname, "0x0210", "LATIN CAPITAL LETTER R WITH DOUBLE GRAVE");
	genSvg(fontname, "0x0211", "LATIN SMALL LETTER R WITH DOUBLE GRAVE");
	genSvg(fontname, "0x0212", "LATIN CAPITAL LETTER R WITH INVERTED BREVE");
	genSvg(fontname, "0x0213", "LATIN SMALL LETTER R WITH INVERTED BREVE");
	genSvg(fontname, "0x0214", "LATIN CAPITAL LETTER U WITH DOUBLE GRAVE");
	genSvg(fontname, "0x0215", "LATIN SMALL LETTER U WITH DOUBLE GRAVE");
	genSvg(fontname, "0x0216", "LATIN CAPITAL LETTER U WITH INVERTED BREVE");
	genSvg(fontname, "0x0217", "LATIN SMALL LETTER U WITH INVERTED BREVE");

	// Romanian
	genSvg(fontname, "0x0218", "LATIN CAPITAL LETTER S WITH COMMA BELOW");
	genSvg(fontname, "0x0219", "LATIN SMALL LETTER S WITH COMMA BELOW");
	genSvg(fontname, "0x021A", "LATIN CAPITAL LETTER T WITH COMMA BELOW");
	genSvg(fontname, "0x021B", "LATIN SMALL LETTER T WITH COMMA BELOW");

	// Miscellaneous
	genSvg(fontname, "0x021C", "LATIN CAPITAL LETTER YOGH");
	genSvg(fontname, "0x021D", "LATIN SMALL LETTER YOGH");
	genSvg(fontname, "0x021E", "LATIN CAPITAL LETTER H WITH CARON");
	genSvg(fontname, "0x021F", "LATIN SMALL LETTER H WITH CARON");
	genSvg(fontname, "0x0220", "LATIN CAPITAL LETTER N WITH LONG RIGHT LEG");
	genSvg(fontname, "0x0221", "LATIN SMALL LETTER D WITH CURL");
	genSvg(fontname, "0x0222", "LATIN CAPITAL LETTER OU");
	genSvg(fontname, "0x0223", "LATIN SMALL LETTER OU");
	genSvg(fontname, "0x0224", "LATIN CAPITAL LETTER Z WITH HOOK");
	genSvg(fontname, "0x0225", "LATIN SMALL LETTER Z WITH HOOK");
	genSvg(fontname, "0x0226", "LATIN CAPITAL LETTER A WITH DOT ABOVE");
	genSvg(fontname, "0x0227", "LATIN SMALL LETTER A WITH DOT ABOVE");
	genSvg(fontname, "0x0228", "LATIN CAPITAL LETTER E WITH CEDILLA");
	genSvg(fontname, "0x0229", "LATIN SMALL LETTER E WITH CEDILLA");

	// Livonian
	genSvg(fontname, "0x022A", "LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON");
	genSvg(fontname, "0x022B", "LATIN SMALL LETTER O WITH DIAERESIS AND MACRON");
	genSvg(fontname, "0x022C", "LATIN CAPITAL LETTER O WITH TILDE AND MACRON");
	genSvg(fontname, "0x022D", "LATIN SMALL LETTER O WITH TILDE AND MACRON");
	genSvg(fontname, "0x022E", "LATIN CAPITAL LETTER O WITH DOT ABOVE");
	genSvg(fontname, "0x022F", "LATIN SMALL LETTER O WITH DOT ABOVE");
	genSvg(fontname, "0x0230", "LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON");
	genSvg(fontname, "0x0231", "LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON");
	genSvg(fontname, "0x0232", "LATIN CAPITAL LETTER Y WITH MACRON");
	genSvg(fontname, "0x0233", "LATIN SMALL LETTER Y WITH MACRON");

	// Sinology
	genSvg(fontname, "0x0234", "LATIN SMALL LETTER L WITH CURL");
	genSvg(fontname, "0x0235", "LATIN SMALL LETTER N WITH CURL");
	genSvg(fontname, "0x0236", "LATIN SMALL LETTER T WITH CURL");

	// Miscellaneous
	genSvg(fontname, "0x0237", "LATIN SMALL LETTER DOTLESS J");
	genSvg(fontname, "0x0238", "LATIN SMALL LETTER DB DIGRAPH");
	genSvg(fontname, "0x0239", "LATIN SMALL LETTER QP DIGRAPH");
	genSvg(fontname, "0x023A", "LATIN CAPITAL LETTER A WITH STROKE");
	genSvg(fontname, "0x023B", "LATIN CAPITAL LETTER C WITH STROKE");
	genSvg(fontname, "0x023C", "LATIN SMALL LETTER C WITH STROKE");
	genSvg(fontname, "0x023D", "LATIN CAPITAL LETTER L WITH BAR");
	genSvg(fontname, "0x023E", "LATIN CAPITAL LETTER T WITH DIAGONAL STROKE");
	genSvg(fontname, "0x023F", "LATIN SMALL LETTER S WITH SWASH TAIL");
	genSvg(fontname, "0x0240", "LATIN SMALL LETTER Z WITH SWASH TAIL");
	genSvg(fontname, "0x0241", "LATIN CAPITAL LETTER GLOTTAL STOP");
	genSvg(fontname, "0x0242", "LATIN SMALL LETTER GLOTTAL STOP");
	genSvg(fontname, "0x0243", "LATIN CAPITAL LETTER B WITH STROKE");
	genSvg(fontname, "0x0244", "LATIN CAPITAL LETTER U BAR");
	genSvg(fontname, "0x0245", "LATIN CAPITAL LETTER TURNED V");
	genSvg(fontname, "0x0246", "LATIN CAPITAL LETTER E WITH STROKE");
	genSvg(fontname, "0x0247", "LATIN SMALL LETTER E WITH STROKE");
	genSvg(fontname, "0x0248", "LATIN CAPITAL LETTER J WITH STROKE");
	genSvg(fontname, "0x0249", "LATIN SMALL LETTER J WITH STROKE");
	genSvg(fontname, "0x024A", "LATIN CAPITAL LETTER Q WITH HOOK TAIL");
	genSvg(fontname, "0x024B", "LATIN SMALL LETTER Q WITH HOOK TAIL");
	genSvg(fontname, "0x024C", "LATIN CAPITAL LETTER R WITH STROKE");
	genSvg(fontname, "0x024D", "LATIN SMALL LETTER R WITH STROKE");
	genSvg(fontname, "0x024E", "LATIN CAPITAL LETTER Y WITH STROKE");
	genSvg(fontname, "0x024F", "LATIN SMALL LETTER Y WITH STROKE");

	// -=- Latin Extended Additional

	genSvg(fontname, "0x1E02", "LATIN CAPITAL LETTER B WITH DOT ABOVE");
	genSvg(fontname, "0x1E03", "LATIN SMALL LETTER B WITH DOT ABOVE");
	genSvg(fontname, "0x1E0A", "LATIN CAPITAL LETTER D WITH DOT ABOVE");
	genSvg(fontname, "0x1E0B", "LATIN SMALL LETTER D WITH DOT ABOVE");
	genSvg(fontname, "0x1E1E", "LATIN CAPITAL LETTER F WITH DOT ABOVE");
	genSvg(fontname, "0x1E1F", "LATIN SMALL LETTER F WITH DOT ABOVE");
	genSvg(fontname, "0x1E40", "LATIN CAPITAL LETTER M WITH DOT ABOVE");
	genSvg(fontname, "0x1E41", "LATIN SMALL LETTER M WITH DOT ABOVE");
	genSvg(fontname, "0x1E56", "LATIN CAPITAL LETTER P WITH DOT ABOVE");
	genSvg(fontname, "0x1E57", "LATIN SMALL LETTER P WITH DOT ABOVE");
	genSvg(fontname, "0x1E60", "LATIN CAPITAL LETTER S WITH DOT ABOVE");
	genSvg(fontname, "0x1E61", "LATIN SMALL LETTER S WITH DOT ABOVE");
	genSvg(fontname, "0x1E6A", "LATIN CAPITAL LETTER T WITH DOT ABOVE");
	genSvg(fontname, "0x1E6B", "LATIN SMALL LETTER T WITH DOT ABOVE");
	genSvg(fontname, "0x1E80", "LATIN CAPITAL LETTER W WITH GRAVE");
	genSvg(fontname, "0x1E81", "LATIN SMALL LETTER W WITH GRAVE");
	genSvg(fontname, "0x1E82", "LATIN CAPITAL LETTER W WITH ACUTE");
	genSvg(fontname, "0x1E83", "LATIN SMALL LETTER W WITH ACUTE");
	genSvg(fontname, "0x1E84", "LATIN CAPITAL LETTER W WITH DIAERESIS");
	genSvg(fontname, "0x1E85", "LATIN SMALL LETTER W WITH DIAERESIS");
	genSvg(fontname, "0x1E9B", "LATIN SMALL LETTER LONG S WITH DOT ABOVE");
	genSvg(fontname, "0x1EF2", "LATIN CAPITAL LETTER Y WITH GRAVE");
	genSvg(fontname, "0x1EF3", "LATIN SMALL LETTER Y WITH GRAVE");

	// -=- IPA Extensions

	genSvg(fontname, "0x0259", "LATIN SMALL LETTER SCHWA");
	genSvg(fontname, "0x027C", "LATIN SMALL LETTER R WITH LONG LEG");
	genSvg(fontname, "0x0292", "LATIN SMALL LETTER EZH");

	// -=- Spacing Modifier Letters

	genSvg(fontname, "0x02B0", "MODIFIER LETTER SMALL H");
	genSvg(fontname, "0x02B1", "MODIFIER LETTER SMALL H WITH HOOK");
	genSvg(fontname, "0x02B2", "MODIFIER LETTER SMALL J");
	genSvg(fontname, "0x02B3", "MODIFIER LETTER SMALL R");
	genSvg(fontname, "0x02B4", "MODIFIER LETTER SMALL TURNED R");
	genSvg(fontname, "0x02B5", "MODIFIER LETTER SMALL TURNED R WITH HOOK");
	genSvg(fontname, "0x02B6", "MODIFIER LETTER SMALL CAPITAL INVERTED R");
	genSvg(fontname, "0x02B7", "MODIFIER LETTER SMALL W");
	genSvg(fontname, "0x02B8", "MODIFIER LETTER SMALL Y");
	genSvg(fontname, "0x02B9", "MODIFIER LETTER PRIME");
	genSvg(fontname, "0x02BA", "MODIFIER LETTER DOUBLE PRIME");
	genSvg(fontname, "0x02BB", "MODIFIER LETTER TURNED COMMA");
	genSvg(fontname, "0x02BC", "MODIFIER LETTER APOSTROPHE");
	genSvg(fontname, "0x02BD", "MODIFIER LETTER REVERSED COMMA");
	genSvg(fontname, "0x02BE", "MODIFIER LETTER RIGHT HALF RING");
	genSvg(fontname, "0x02BF", "MODIFIER LETTER LEFT HALF RING");
	genSvg(fontname, "0x02C0", "MODIFIER LETTER GLOTTAL STOP");
	genSvg(fontname, "0x02C1", "MODIFIER LETTER REVERSED GLOTTAL STOP");
	genSvg(fontname, "0x02C2", "MODIFIER LETTER LEFT ARROWHEAD");
	genSvg(fontname, "0x02C3", "MODIFIER LETTER RIGHT ARROWHEAD");
	genSvg(fontname, "0x02C4", "MODIFIER LETTER UP ARROWHEAD");
	genSvg(fontname, "0x02C5", "MODIFIER LETTER DOWN ARROWHEAD");
	genSvg(fontname, "0x02C6", "MODIFIER LETTER CIRCUMFLEX ACCENT");
	genSvg(fontname, "0x02C7", "CARON");
	genSvg(fontname, "0x02C8", "MODIFIER LETTER VERTICAL LINE");
	genSvg(fontname, "0x02C9", "MODIFIER LETTER MACRON");
	genSvg(fontname, "0x02CA", "MODIFIER LETTER ACUTE ACCENT");
	genSvg(fontname, "0x02CB", "MODIFIER LETTER GRAVE ACCENT");
	genSvg(fontname, "0x02CC", "MODIFIER LETTER LOW VERTICAL LINE");
	genSvg(fontname, "0x02CD", "MODIFIER LETTER LOW MACRON");
	genSvg(fontname, "0x02CE", "MODIFIER LETTER LOW GRAVE ACCENT");
	genSvg(fontname, "0x02CF", "MODIFIER LETTER LOW ACUTE ACCENT");
	genSvg(fontname, "0x02D0", "MODIFIER LETTER TRIANGULAR COLON");
	genSvg(fontname, "0x02D1", "MODIFIER LETTER HALF TRIANGULAR COLON");
	genSvg(fontname, "0x02D2", "MODIFIER LETTER CENTERED RIGHT HALF RING");
	genSvg(fontname, "0x02D3", "MODIFIER LETTER CENTERED LEFT HALF RING");
	genSvg(fontname, "0x02D4", "MODIFIER LETTER UP TACK");
	genSvg(fontname, "0x02D5", "MODIFIER LETTER DOWN TACK");
	genSvg(fontname, "0x02D6", "MODIFIER LETTER PLUS SIGN");
	genSvg(fontname, "0x02D7", "MODIFIER LETTER MINUS SIGN");
	genSvg(fontname, "0x02D8", "BREVE");
	genSvg(fontname, "0x02D9", "DOT ABOVE");
	genSvg(fontname, "0x02DA", "RING ABOVE");
	genSvg(fontname, "0x02DB", "OGONEK");
	genSvg(fontname, "0x02DC", "SMALL TILDE");
	genSvg(fontname, "0x02DD", "DOUBLE ACUTE ACCENT");
	genSvg(fontname, "0x02DE", "MODIFIER LETTER RHOTIC HOOK");
	genSvg(fontname, "0x02DF", "MODIFIER LETTER CROSS ACCENT");
	genSvg(fontname, "0x02E0", "MODIFIER LETTER SMALL GAMMA");
	genSvg(fontname, "0x02E1", "MODIFIER LETTER SMALL L");
	genSvg(fontname, "0x02E2", "MODIFIER LETTER SMALL S");
	genSvg(fontname, "0x02E3", "MODIFIER LETTER SMALL X");
	genSvg(fontname, "0x02E4", "MODIFIER LETTER SMALL REVERSED GLOTTAL STOP");
	genSvg(fontname, "0x02E5", "MODIFIER LETTER EXTRA-HIGH TONE BAR");
	genSvg(fontname, "0x02E6", "MODIFIER LETTER HIGH TONE BAR");
	genSvg(fontname, "0x02E7", "MODIFIER LETTER MID TONE BAR");
	genSvg(fontname, "0x02E8", "MODIFIER LETTER LOW TONE BAR");
	genSvg(fontname, "0x02E9", "MODIFIER LETTER EXTRA-LOW TONE BAR");
	genSvg(fontname, "0x02EA", "MODIFIER LETTER YIN DEPARTING TONE MARK");
	genSvg(fontname, "0x02EB", "MODIFIER LETTER YANG DEPARTING TONE MARK");
	genSvg(fontname, "0x02EC", "MODIFIER LETTER VOICING");
	genSvg(fontname, "0x02ED", "MODIFIER LETTER UNASPIRATED");
	genSvg(fontname, "0x02EE", "MODIFIER LETTER DOUBLE APOSTROPHE");
	genSvg(fontname, "0x02EF", "MODIFIER LETTER LOW DOWN ARROWHEAD");
	genSvg(fontname, "0x02F0", "MODIFIER LETTER LOW UP ARROWHEAD");
	genSvg(fontname, "0x02F1", "MODIFIER LETTER LOW LEFT ARROWHEAD");
	genSvg(fontname, "0x02F2", "MODIFIER LETTER LOW RIGHT ARROWHEAD");
	genSvg(fontname, "0x02F3", "MODIFIER LETTER LOW RING");
	genSvg(fontname, "0x02F4", "MODIFIER LETTER MIDDLE GRAVE ACCENT");
	genSvg(fontname, "0x02F5", "MODIFIER LETTER MIDDLE DOUBLE GRAVE ACCENT");
	genSvg(fontname, "0x02F6", "MODIFIER LETTER MIDDLE DOUBLE ACUTE ACCENT");
	genSvg(fontname, "0x02F7", "MODIFIER LETTER LOW TILDE");
	genSvg(fontname, "0x02F8", "MODIFIER LETTER RAISED COLON");
	genSvg(fontname, "0x02F9", "MODIFIER LETTER BEGIN HIGH TONE");
	genSvg(fontname, "0x02FA", "MODIFIER LETTER END HIGH TONE");
	genSvg(fontname, "0x02FB", "MODIFIER LETTER BEGIN LOW TONE");
	genSvg(fontname, "0x02FC", "MODIFIER LETTER END LOW TONE");
	genSvg(fontname, "0x02FD", "MODIFIER LETTER SHELF");
	genSvg(fontname, "0x02FE", "MODIFIER LETTER OPEN SHELF");
	genSvg(fontname, "0x02FF", "MODIFIER LETTER LOW LEFT ARROW");

	// -=- Greek and Coptic

	genSvg(fontname, "0x0370", "GREEK CAPITAL LETTER HETA");
	genSvg(fontname, "0x0371", "GREEK SMALL LETTER HETA");
	genSvg(fontname, "0x0372", "GREEK CAPITAL LETTER ARCHAIC SAMPI");
	genSvg(fontname, "0x0373", "GREEK SMALL LETTER ARCHAIC SAMPI");
	genSvg(fontname, "0x0374", "GREEK NUMERAL SIGN");
	genSvg(fontname, "0x0375", "GREEK LOWER NUMERAL SIGN");
	genSvg(fontname, "0x0376", "GREEK CAPITAL LETTER PAMPHYLIAN DIGAMMA");
	genSvg(fontname, "0x0377", "GREEK SMALL LETTER PAMPHYLIAN DIGAMMA");
	genSvg(fontname, "0x037A", "GREEK YPOGEGRAMMENI");
	genSvg(fontname, "0x037B", "GREEK SMALL REVERSED LUNATE SIGMA SYMBOL");
	genSvg(fontname, "0x037C", "GREEK SMALL DOTTED LUNATE SIGMA SYMBOL");
	genSvg(fontname, "0x037D", "GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL");
	genSvg(fontname, "0x037E", "GREEK QUESTION MARK");
	genSvg(fontname, "0x037F", "GREEK CAPITAL LETTER YOT");
	genSvg(fontname, "0x0384", "GREEK ACUTE ACCENT (TONOS)");
	genSvg(fontname, "0x0385", "GREEK DIAERESIS WITH ACUTE ACCENT");
	genSvg(fontname, "0x0386", "GREEK CAPITAL LETTER A WITH ACUTE ACCENT");
	genSvg(fontname, "0x0387", "GREEK ANO TELEIA");
	genSvg(fontname, "0x0388", "GREEK CAPITAL LETTER EPSILON WITH ACUTE ACCENT");
	genSvg(fontname, "0x0389", "GREEK CAPITAL LETTER ETA WITH ACUTE ACCENT");
	genSvg(fontname, "0x038A", "GREEK CAPITAL LETTER IOTA WITH ACUTE ACCENT");
	genSvg(fontname, "0x038C", "GREEK CAPITAL LETTER OMICRON WITH ACUTE ACCENT");
	genSvg(fontname, "0x038E", "GREEK CAPITAL LETTER UPSILON WITH ACUTE ACCENT");
	genSvg(fontname, "0x038F", "GREEK CAPITAL LETTER OMEGA WITH ACUTE ACCENT");
	genSvg(fontname, "0x0390", "GREEK SMALL LETTER IOTA WITH DIAERESIS AND ACUTE ACCENT");
	genSvg(fontname, "0x0391", "GREEK CAPITAL LETTER ALPHA");
	genSvg(fontname, "0x0392", "GREEK CAPITAL LETTER BETA");
	genSvg(fontname, "0x0393", "GREEK CAPITAL LETTER GAMMA");
	genSvg(fontname, "0x0394", "GREEK CAPITAL LETTER DELTA");
	genSvg(fontname, "0x0395", "GREEK CAPITAL LETTER EPSILON");
	genSvg(fontname, "0x0396", "GREEK CAPITAL LETTER ZETA");
	genSvg(fontname, "0x0397", "GREEK CAPITAL LETTER ETA");
	genSvg(fontname, "0x0398", "GREEK CAPITAL LETTER THETA");
	genSvg(fontname, "0x0399", "GREEK CAPITAL LETTER IOTA");
	genSvg(fontname, "0x039A", "GREEK CAPITAL LETTER KAPPA");
	genSvg(fontname, "0x039B", "GREEK CAPITAL LETTER LAMBDA");
	genSvg(fontname, "0x039C", "GREEK CAPITAL LETTER MU");
	genSvg(fontname, "0x039D", "GREEK CAPITAL LETTER NU");
	genSvg(fontname, "0x039E", "GREEK CAPITAL LETTER XI");
	genSvg(fontname, "0x039F", "GREEK CAPITAL LETTER OMICRON");
	genSvg(fontname, "0x03A0", "GREEK CAPITAL LETTER PI");
	genSvg(fontname, "0x03A1", "GREEK CAPITAL LETTER RHO");
	genSvg(fontname, "0x03A3", "GREEK CAPITAL LETTER SIGMA");
	genSvg(fontname, "0x03A4", "GREEK CAPITAL LETTER TAU");
	genSvg(fontname, "0x03A5", "GREEK CAPITAL LETTER UPSILON");
	genSvg(fontname, "0x03A6", "GREEK CAPITAL LETTER PHI");
	genSvg(fontname, "0x03A7", "GREEK CAPITAL LETTER CHI");
	genSvg(fontname, "0x03A8", "GREEK CAPITAL LETTER PSI");
	genSvg(fontname, "0x03A9", "GREEK CAPITAL LETTER OMEGA");
	genSvg(fontname, "0x03AA", "GREEK CAPITAL LETTER IOTA WITH DIAERESIS");
	genSvg(fontname, "0x03AB", "GREEK CAPITAL LETTER UPSILON WITH DIAERESIS");
	genSvg(fontname, "0x03AC", "GREEK SMALL LETTER ALPHA WITH ACUTE ACCENT");
	genSvg(fontname, "0x03AD", "GREEK SMALL LETTER EPSILON WITH ACUTE ACCENT");
	genSvg(fontname, "0x03AE", "GREEK SMALL LETTER ETA WITH ACUTE ACCENT");
	genSvg(fontname, "0x03AF", "GREEK SMALL LETTER IOTA WITH ACUTE ACCENT");
	genSvg(fontname, "0x03B0", "GREEK SMALL LETTER UPSILON WITH DIAERESIS AND ACUTE ACCENT");
	genSvg(fontname, "0x03B1", "GREEK SMALL LETTER ALPHA");
	genSvg(fontname, "0x03B2", "GREEK SMALL LETTER BETA");
	genSvg(fontname, "0x03B3", "GREEK SMALL LETTER GAMMA");
	genSvg(fontname, "0x03B4", "GREEK SMALL LETTER DELTA");
	genSvg(fontname, "0x03B5", "GREEK SMALL LETTER EPSILON");
	genSvg(fontname, "0x03B6", "GREEK SMALL LETTER ZETA");
	genSvg(fontname, "0x03B7", "GREEK SMALL LETTER ETA");
	genSvg(fontname, "0x03B8", "GREEK SMALL LETTER THETA");
	genSvg(fontname, "0x03B9", "GREEK SMALL LETTER IOTA");
	genSvg(fontname, "0x03BA", "GREEK SMALL LETTER KAPPA");
	genSvg(fontname, "0x03BB", "GREEK SMALL LETTER LAMBDA");
	genSvg(fontname, "0x03BC", "GREEK SMALL LETTER MU");
	genSvg(fontname, "0x03BD", "GREEK SMALL LETTER NU");
	genSvg(fontname, "0x03BE", "GREEK SMALL LETTER XI");
	genSvg(fontname, "0x03BF", "GREEK SMALL LETTER OMICRON");
	genSvg(fontname, "0x03C0", "GREEK SMALL LETTER PI");
	genSvg(fontname, "0x03C1", "GREEK SMALL LETTER RHO");
	genSvg(fontname, "0x03C2", "GREEK SMALL LETTER FINAL SIGMA");
	genSvg(fontname, "0x03C3", "GREEK SMALL LETTER SIGMA");
	genSvg(fontname, "0x03C4", "GREEK SMALL LETTER TAU");
	genSvg(fontname, "0x03C5", "GREEK SMALL LETTER UPSILON");
	genSvg(fontname, "0x03C6", "GREEK SMALL LETTER PHI");
	genSvg(fontname, "0x03C7", "GREEK SMALL LETTER CHI");
	genSvg(fontname, "0x03C8", "GREEK SMALL LETTER PSI");
	genSvg(fontname, "0x03C9", "GREEK SMALL LETTER OMEGA");
	genSvg(fontname, "0x03CA", "GREEK SMALL LETTER IOTA WITH DIAERESIS");
	genSvg(fontname, "0x03CB", "GREEK SMALL LETTER UPSILON WITH DIAERESIS");
	genSvg(fontname, "0x03CC", "GREEK SMALL LETTER OMICRON WITH ACUTE ACCENT");
	genSvg(fontname, "0x03CD", "GREEK SMALL LETTER UPSILON WITH ACUTE ACCENT");
	genSvg(fontname, "0x03CE", "GREEK SMALL LETTER OMEGA WITH ACUTE ACCENT");
	genSvg(fontname, "0x03CF", "GREEK CAPITAL KAI SYMBOL");
	genSvg(fontname, "0x03D0", "GREEK BETA SYMBOL");
	genSvg(fontname, "0x03D1", "GREEK THETA SYMBOL");
	genSvg(fontname, "0x03D2", "GREEK UPSILON WITH HOOK SYMBOL");
	genSvg(fontname, "0x03D3", "GREEK UPSILON WITH ACUTE AND HOOK SYMBOL");
	genSvg(fontname, "0x03D4", "GREEK UPSILON WITH DIAERESIS AND HOOK SYMBOL");
	genSvg(fontname, "0x03D5", "GREEK PHI SYMBOL");
	genSvg(fontname, "0x03D6", "GREEK PI SYMBOL");
	genSvg(fontname, "0x03D7", "GREEK KAI SYMBOL");
	genSvg(fontname, "0x03D8", "GREEK LETTER QOPPA");
	genSvg(fontname, "0x03D9", "GREEK SMALL LETTER QOPPA");
	genSvg(fontname, "0x03DA", "GREEK LETTER STIGMA (LETTER)");
	genSvg(fontname, "0x03DB", "GREEK SMALL LETTER STIGMA");
	genSvg(fontname, "0x03DC", "GREEK LETTER DIGAMMA");
	genSvg(fontname, "0x03DD", "GREEK SMALL LETTER DIGAMMA");
	genSvg(fontname, "0x03DE", "GREEK LETTER KOPPA");
	genSvg(fontname, "0x03DF", "GREEK SMALL LETTER KOPPA");
	genSvg(fontname, "0x03E0", "GREEK LETTER SAMPI");
	genSvg(fontname, "0x03E1", "GREEK SMALL LETTER SAMPI");
	genSvg(fontname, "0x03E2", "COPTIC CAPITAL LETTER SHEI");
	genSvg(fontname, "0x03E3", "COPTIC SMALL LETTER SHEI");
	genSvg(fontname, "0x03E4", "COPTIC CAPITAL LETTER FEI");
	genSvg(fontname, "0x03E5", "COPTIC SMALL LETTER FEI");
	genSvg(fontname, "0x03E6", "COPTIC CAPITAL LETTER KHEI");
	genSvg(fontname, "0x03E7", "COPTIC SMALL LETTER KHEI");
	genSvg(fontname, "0x03E8", "COPTIC CAPITAL LETTER HORI");
	genSvg(fontname, "0x03E9", "COPTIC SMALL LETTER HORI");
	genSvg(fontname, "0x03EA", "COPTIC CAPITAL LETTER GANGIA");
	genSvg(fontname, "0x03EB", "COPTIC SMALL LETTER GANGIA");
	genSvg(fontname, "0x03EC", "COPTIC CAPITAL LETTER SHIMA");
	genSvg(fontname, "0x03ED", "COPTIC SMALL LETTER SHIMA");
	genSvg(fontname, "0x03EE", "COPTIC CAPITAL LETTER DEI");
	genSvg(fontname, "0x03EF", "COPTIC SMALL LETTER DEI");
	genSvg(fontname, "0x03F0", "GREEK KAPPA SYMBOL");
	genSvg(fontname, "0x03F1", "GREEK RHO SYMBOL");
	genSvg(fontname, "0x03F2", "GREEK LUNATE SIGMA SYMBOL");
	genSvg(fontname, "0x03F3", "GREEK LETTER YOT");
	genSvg(fontname, "0x03F4", "GREEK CAPITAL THETA SYMBOL");
	genSvg(fontname, "0x03F5", "GREEK LUNATE EPSILON SYMBOL");
	genSvg(fontname, "0x03F6", "GREEK REVERSED LUNATE EPSILON SYMBOL");
	genSvg(fontname, "0x03F7", "GREEK CAPITAL SHO");
	genSvg(fontname, "0x03F8", "GREEK SMALL LETTER SHO");
	genSvg(fontname, "0x03F9", "GREEK CAPITAL LUNATE SIGMA SYMBOL");
	genSvg(fontname, "0x03FA", "GREEK CAPITAL SAN");
	genSvg(fontname, "0x03FB", "GREEK SMALL LETTER SAN");
	genSvg(fontname, "0x03FC", "GREEK RHO WITH STROKE SYMBOL");
	genSvg(fontname, "0x03FD", "GREEK CAPITAL REVERSED LUNATE SIGMA SYMBOL");
	genSvg(fontname, "0x03FE", "GREEK CAPITAL DOTTED LUNATE SIGMA SYMBOL");
	genSvg(fontname, "0x03FF", "GREEK CAPITAL REVERSED DOTTED LUNATE SIGMA SYMBOL");

	// -=- Cyrillic

	genSvg(fontname, "0x0400", "CYRILLIC CAPITAL LETTER IE WITH GRAVE");
	genSvg(fontname, "0x0401", "CYRILLIC CAPITAL LETTER IO");
	genSvg(fontname, "0x0402", "CYRILLIC CAPITAL LETTER DJE");
	genSvg(fontname, "0x0403", "CYRILLIC CAPITAL LETTER GJE");
	genSvg(fontname, "0x0404", "CYRILLIC CAPITAL LETTER UKRAINIAN IE");
	genSvg(fontname, "0x0405", "CYRILLIC CAPITAL LETTER DZE");
	genSvg(fontname, "0x0406", "CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I");
	genSvg(fontname, "0x0407", "CYRILLIC CAPITAL LETTER YI");
	genSvg(fontname, "0x0408", "CYRILLIC CAPITAL LETTER JE");
	genSvg(fontname, "0x0409", "CYRILLIC CAPITAL LETTER LJE");
	genSvg(fontname, "0x040A", "CYRILLIC CAPITAL LETTER NJE");
	genSvg(fontname, "0x040B", "CYRILLIC CAPITAL LETTER TSHE");
	genSvg(fontname, "0x040C", "CYRILLIC CAPITAL LETTER KJE");
	genSvg(fontname, "0x040D", "CYRILLIC CAPITAL LETTER I WITH GRAVE");
	genSvg(fontname, "0x040E", "CYRILLIC CAPITAL LETTER SHORT U");
	genSvg(fontname, "0x040F", "CYRILLIC CAPITAL LETTER DZHE");
	genSvg(fontname, "0x0410", "CYRILLIC CAPITAL LETTER A");
	genSvg(fontname, "0x0411", "CYRILLIC CAPITAL LETTER BE");
	genSvg(fontname, "0x0412", "CYRILLIC CAPITAL LETTER VE");
	genSvg(fontname, "0x0413", "CYRILLIC CAPITAL LETTER GHE");
	genSvg(fontname, "0x0414", "CYRILLIC CAPITAL LETTER DE");
	genSvg(fontname, "0x0415", "CYRILLIC CAPITAL LETTER IE");
	genSvg(fontname, "0x0416", "CYRILLIC CAPITAL LETTER ZHE");
	genSvg(fontname, "0x0417", "CYRILLIC CAPITAL LETTER ZE");
	genSvg(fontname, "0x0418", "CYRILLIC CAPITAL LETTER I");
	genSvg(fontname, "0x0419", "CYRILLIC CAPITAL LETTER SHORT I");
	genSvg(fontname, "0x041A", "CYRILLIC CAPITAL LETTER KA");
	genSvg(fontname, "0x041B", "CYRILLIC CAPITAL LETTER EL");
	genSvg(fontname, "0x041C", "CYRILLIC CAPITAL LETTER EM");
	genSvg(fontname, "0x041D", "CYRILLIC CAPITAL LETTER EN");
	genSvg(fontname, "0x041E", "CYRILLIC CAPITAL LETTER O");
	genSvg(fontname, "0x041F", "CYRILLIC CAPITAL LETTER PE");
	genSvg(fontname, "0x0420", "CYRILLIC CAPITAL LETTER ER");
	genSvg(fontname, "0x0421", "CYRILLIC CAPITAL LETTER ES");
	genSvg(fontname, "0x0422", "CYRILLIC CAPITAL LETTER TE");
	genSvg(fontname, "0x0423", "CYRILLIC CAPITAL LETTER U");
	genSvg(fontname, "0x0424", "CYRILLIC CAPITAL LETTER EF");
	genSvg(fontname, "0x0425", "CYRILLIC CAPITAL LETTER HA");
	genSvg(fontname, "0x0426", "CYRILLIC CAPITAL LETTER TSE");
	genSvg(fontname, "0x0427", "CYRILLIC CAPITAL LETTER CHE");
	genSvg(fontname, "0x0428", "CYRILLIC CAPITAL LETTER SHA");
	genSvg(fontname, "0x0429", "CYRILLIC CAPITAL LETTER SHCHA");
	genSvg(fontname, "0x042A", "CYRILLIC CAPITAL LETTER HARD SIGN");
	genSvg(fontname, "0x042B", "CYRILLIC CAPITAL LETTER YERU");
	genSvg(fontname, "0x042C", "CYRILLIC CAPITAL LETTER SOFT SIGN");
	genSvg(fontname, "0x042D", "CYRILLIC CAPITAL LETTER E");
	genSvg(fontname, "0x042E", "CYRILLIC CAPITAL LETTER YU");
	genSvg(fontname, "0x042F", "CYRILLIC CAPITAL LETTER YA");
	genSvg(fontname, "0x0430", "CYRILLIC SMALL LETTER A");
	genSvg(fontname, "0x0431", "CYRILLIC SMALL LETTER BE");
	genSvg(fontname, "0x0432", "CYRILLIC SMALL LETTER VE");
	genSvg(fontname, "0x0433", "CYRILLIC SMALL LETTER GHE");
	genSvg(fontname, "0x0434", "CYRILLIC SMALL LETTER DE");
	genSvg(fontname, "0x0435", "CYRILLIC SMALL LETTER IE");
	genSvg(fontname, "0x0436", "CYRILLIC SMALL LETTER ZHE");
	genSvg(fontname, "0x0437", "CYRILLIC SMALL LETTER ZE");
	genSvg(fontname, "0x0438", "CYRILLIC SMALL LETTER I");
	genSvg(fontname, "0x0439", "CYRILLIC SMALL LETTER SHORT I");
	genSvg(fontname, "0x043A", "CYRILLIC SMALL LETTER KA");
	genSvg(fontname, "0x043B", "CYRILLIC SMALL LETTER EL");
	genSvg(fontname, "0x043C", "CYRILLIC SMALL LETTER EM");
	genSvg(fontname, "0x043D", "CYRILLIC SMALL LETTER EN");
	genSvg(fontname, "0x043E", "CYRILLIC SMALL LETTER O");
	genSvg(fontname, "0x043F", "CYRILLIC SMALL LETTER PE");
	genSvg(fontname, "0x0440", "CYRILLIC SMALL LETTER ER");
	genSvg(fontname, "0x0441", "CYRILLIC SMALL LETTER ES");
	genSvg(fontname, "0x0442", "CYRILLIC SMALL LETTER TE");
	genSvg(fontname, "0x0443", "CYRILLIC SMALL LETTER U");
	genSvg(fontname, "0x0444", "CYRILLIC SMALL LETTER EF");
	genSvg(fontname, "0x0445", "CYRILLIC SMALL LETTER HA");
	genSvg(fontname, "0x0446", "CYRILLIC SMALL LETTER TSE");
	genSvg(fontname, "0x0447", "CYRILLIC SMALL LETTER CHE");
	genSvg(fontname, "0x0448", "CYRILLIC SMALL LETTER SHA");
	genSvg(fontname, "0x0449", "CYRILLIC SMALL LETTER SHCHA");
	genSvg(fontname, "0x044A", "CYRILLIC SMALL LETTER HARD SIGN");
	genSvg(fontname, "0x044B", "CYRILLIC SMALL LETTER YERU");
	genSvg(fontname, "0x044C", "CYRILLIC SMALL LETTER SOFT SIGN");
	genSvg(fontname, "0x044D", "CYRILLIC SMALL LETTER E");
	genSvg(fontname, "0x044E", "CYRILLIC SMALL LETTER YU");
	genSvg(fontname, "0x044F", "CYRILLIC SMALL LETTER YA");
	genSvg(fontname, "0x0450", "CYRILLIC SMALL LETTER IE WITH GRAVE");
	genSvg(fontname, "0x0451", "CYRILLIC SMALL LETTER IO");
	genSvg(fontname, "0x0452", "CYRILLIC SMALL LETTER DJE");
	genSvg(fontname, "0x0453", "CYRILLIC SMALL LETTER GJE");
	genSvg(fontname, "0x0454", "CYRILLIC SMALL LETTER UKRAINIAN IE");
	genSvg(fontname, "0x0455", "CYRILLIC SMALL LETTER DZE");
	genSvg(fontname, "0x0456", "CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I");
	genSvg(fontname, "0x0457", "CYRILLIC SMALL LETTER YI");
	genSvg(fontname, "0x0458", "CYRILLIC SMALL LETTER JE");
	genSvg(fontname, "0x0459", "CYRILLIC SMALL LETTER LJE");
	genSvg(fontname, "0x045A", "CYRILLIC SMALL LETTER NJE");
	genSvg(fontname, "0x045B", "CYRILLIC SMALL LETTER TSHE");
	genSvg(fontname, "0x045C", "CYRILLIC SMALL LETTER KJE");
	genSvg(fontname, "0x045D", "CYRILLIC SMALL LETTER I WITH GRAVE");
	genSvg(fontname, "0x045E", "CYRILLIC SMALL LETTER SHORT U");
	genSvg(fontname, "0x045F", "CYRILLIC SMALL LETTER DZHE");
	genSvg(fontname, "0x0460", "CYRILLIC CAPITAL LETTER OMEGA");
	genSvg(fontname, "0x0461", "CYRILLIC SMALL LETTER OMEGA");
	genSvg(fontname, "0x0462", "CYRILLIC CAPITAL LETTER YAT");
	genSvg(fontname, "0x0463", "CYRILLIC SMALL LETTER YAT");
	genSvg(fontname, "0x0464", "CYRILLIC CAPITAL LETTER IOTIFIED E");
	genSvg(fontname, "0x0465", "CYRILLIC SMALL LETTER IOTIFIED E");
	genSvg(fontname, "0x0466", "CYRILLIC CAPITAL LETTER LITTLE YUS");
	genSvg(fontname, "0x0467", "CYRILLIC SMALL LETTER LITTLE YUS");
	genSvg(fontname, "0x0468", "CYRILLIC CAPITAL LETTER IOTIFIED LITTLE YUS");
	genSvg(fontname, "0x0469", "CYRILLIC SMALL LETTER IOTIFIED LITTLE YUS");
	genSvg(fontname, "0x046A", "CYRILLIC CAPITAL LETTER BIG YUS");
	genSvg(fontname, "0x046B", "CYRILLIC SMALL LETTER BIG YUS");
	genSvg(fontname, "0x046C", "CYRILLIC CAPITAL LETTER IOTIFIED BIG YUS");
	genSvg(fontname, "0x046D", "CYRILLIC SMALL LETTER IOTIFIED BIG YUS");
	genSvg(fontname, "0x046E", "CYRILLIC CAPITAL LETTER KSI");
	genSvg(fontname, "0x046F", "CYRILLIC SMALL LETTER KSI");
	genSvg(fontname, "0x0470", "CYRILLIC CAPITAL LETTER PSI");
	genSvg(fontname, "0x0471", "CYRILLIC SMALL LETTER PSI");
	genSvg(fontname, "0x0472", "CYRILLIC CAPITAL LETTER FITA");
	genSvg(fontname, "0x0473", "CYRILLIC SMALL LETTER FITA");
	genSvg(fontname, "0x0474", "CYRILLIC CAPITAL LETTER IZHITSA");
	genSvg(fontname, "0x0475", "CYRILLIC SMALL LETTER IZHITSA");
	genSvg(fontname, "0x0476", "CYRILLIC CAPITAL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT");
	genSvg(fontname, "0x0477", "CYRILLIC SMALL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT");
	genSvg(fontname, "0x0478", "CYRILLIC CAPITAL LETTER UK");
	genSvg(fontname, "0x0479", "CYRILLIC SMALL LETTER UK");
	genSvg(fontname, "0x047A", "CYRILLIC CAPITAL LETTER ROUND OMEGA");
	genSvg(fontname, "0x047B", "CYRILLIC SMALL LETTER ROUND OMEGA");
	genSvg(fontname, "0x047C", "CYRILLIC CAPITAL LETTER OMEGA WITH TITLO");
	genSvg(fontname, "0x047D", "CYRILLIC SMALL LETTER OMEGA WITH TITLO");
	genSvg(fontname, "0x047E", "CYRILLIC CAPITAL LETTER OT");
	genSvg(fontname, "0x047F", "CYRILLIC SMALL LETTER OT");
	genSvg(fontname, "0x0480", "CYRILLIC CAPITAL LETTER KOPPA");
	genSvg(fontname, "0x0481", "CYRILLIC SMALL LETTER KOPPA");
	genSvg(fontname, "0x0482", "CYRILLIC THOUSANDS SIGN");
	genSvg(fontname, "0x0483", "COMBINING CYRILLIC TITLO");
	genSvg(fontname, "0x0484", "COMBINING CYRILLIC PALATALIZATION");
	genSvg(fontname, "0x0485", "COMBINING CYRILLIC DASIA PNEUMATA");
	genSvg(fontname, "0x0486", "COMBINING CYRILLIC PSILI PNEUMATA");
	genSvg(fontname, "0x0487", "COMBINING CYRILLIC POKRYTIE");
	genSvg(fontname, "0x0488", "COMBINING CYRILLIC HUNDRED THOUSANDS SIGN");
	genSvg(fontname, "0x0489", "COMBINING CYRILLIC MILLIONS SIGN");
	genSvg(fontname, "0x048A", "CYRILLIC CAPITAL LETTER SHORT I WITH TAIL");
	genSvg(fontname, "0x048B", "CYRILLIC SMALL LETTER SHORT I WITH TAIL");
	genSvg(fontname, "0x048C", "CYRILLIC CAPITAL LETTER SEMISOFT SIGN");
	genSvg(fontname, "0x048D", "CYRILLIC SMALL LETTER SEMISOFT SIGN");
	genSvg(fontname, "0x048E", "CYRILLIC CAPITAL LETTER ER WITH TICK");
	genSvg(fontname, "0x048F", "CYRILLIC SMALL LETTER ER WITH TICK");
	genSvg(fontname, "0x0490", "CYRILLIC CAPITAL LETTER GHE WITH UPTURN");
	genSvg(fontname, "0x0491", "CYRILLIC SMALL LETTER GHE WITH UPTURN");
	genSvg(fontname, "0x0492", "CYRILLIC CAPITAL LETTER GHE WITH STROKE");
	genSvg(fontname, "0x0493", "CYRILLIC SMALL LETTER GHE WITH STROKE");
	genSvg(fontname, "0x0494", "CYRILLIC CAPITAL LETTER GHE WITH MIDDLE HOOK");
	genSvg(fontname, "0x0495", "CYRILLIC SMALL LETTER GHE WITH MIDDLE HOOK");
	genSvg(fontname, "0x0496", "CYRILLIC CAPITAL LETTER ZHE WITH DESCENDER");
	genSvg(fontname, "0x0497", "CYRILLIC SMALL LETTER ZHE WITH DESCENDER");
	genSvg(fontname, "0x0498", "CYRILLIC CAPITAL LETTER ZE WITH DESCENDER");
	genSvg(fontname, "0x0499", "CYRILLIC SMALL LETTER ZE WITH DESCENDER");
	genSvg(fontname, "0x049A", "CYRILLIC CAPITAL LETTER KA WITH DESCENDER");
	genSvg(fontname, "0x049B", "CYRILLIC SMALL LETTER KA WITH DESCENDER");
	genSvg(fontname, "0x049C", "CYRILLIC CAPITAL LETTER KA WITH VERTICAL STROKE");
	genSvg(fontname, "0x049D", "CYRILLIC SMALL LETTER KA WITH VERTICAL STROKE");
	genSvg(fontname, "0x049E", "CYRILLIC CAPITAL LETTER KA WITH STROKE");
	genSvg(fontname, "0x049F", "CYRILLIC SMALL LETTER KA WITH STROKE");
	genSvg(fontname, "0x04A0", "CYRILLIC CAPITAL LETTER BASHKIR KA");
	genSvg(fontname, "0x04A1", "CYRILLIC SMALL LETTER BASHKIR KA");
	genSvg(fontname, "0x04A2", "CYRILLIC CAPITAL LETTER EN WITH DESCENDER");
	genSvg(fontname, "0x04A3", "CYRILLIC SMALL LETTER EN WITH DESCENDER");
	genSvg(fontname, "0x04A4", "CYRILLIC CAPITAL LIGATURE EN GHE");
	genSvg(fontname, "0x04A5", "CYRILLIC SMALL LIGATURE EN GHE");
	genSvg(fontname, "0x04A6", "CYRILLIC CAPITAL LETTER PE WITH MIDDLE HOOK");
	genSvg(fontname, "0x04A7", "CYRILLIC SMALL LETTER PE WITH MIDDLE HOOK");
	genSvg(fontname, "0x04A8", "CYRILLIC CAPITAL LETTER ABKHAZIAN HA");
	genSvg(fontname, "0x04A9", "CYRILLIC SMALL LETTER ABKHAZIAN HA");
	genSvg(fontname, "0x04AA", "CYRILLIC CAPITAL LETTER ES WITH DESCENDER");
	genSvg(fontname, "0x04AB", "CYRILLIC SMALL LETTER ES WITH DESCENDER");
	genSvg(fontname, "0x04AC", "CYRILLIC CAPITAL LETTER TE WITH DESCENDER");
	genSvg(fontname, "0x04AD", "CYRILLIC SMALL LETTER TE WITH DESCENDER");
	genSvg(fontname, "0x04AE", "CYRILLIC CAPITAL LETTER STRAIGHT U");
	genSvg(fontname, "0x04AF", "CYRILLIC SMALL LETTER STRAIGHT U");
	genSvg(fontname, "0x04B0", "CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE");
	genSvg(fontname, "0x04B1", "CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE");
	genSvg(fontname, "0x04B2", "CYRILLIC CAPITAL LETTER HA WITH DESCENDER");
	genSvg(fontname, "0x04B3", "CYRILLIC SMALL LETTER HA WITH DESCENDER");
	genSvg(fontname, "0x04B4", "CYRILLIC CAPITAL LIGATURE TE TSE");
	genSvg(fontname, "0x04B5", "CYRILLIC SMALL LIGATURE TE TSE");
	genSvg(fontname, "0x04B6", "CYRILLIC CAPITAL LETTER CHE WITH DESCENDER");
	genSvg(fontname, "0x04B7", "CYRILLIC SMALL LETTER CHE WITH DESCENDER");
	genSvg(fontname, "0x04B8", "CYRILLIC CAPITAL LETTER CHE WITH VERTICAL STROKE");
	genSvg(fontname, "0x04B9", "CYRILLIC SMALL LETTER CHE WITH VERTICAL STROKE");
	genSvg(fontname, "0x04BA", "CYRILLIC CAPITAL LETTER SHHA");
	genSvg(fontname, "0x04BB", "CYRILLIC SMALL LETTER SHHA");
	genSvg(fontname, "0x04BC", "CYRILLIC CAPITAL LETTER ABKHAZIAN CHE");
	genSvg(fontname, "0x04BD", "CYRILLIC SMALL LETTER ABKHAZIAN CHE");
	genSvg(fontname, "0x04BE", "CYRILLIC CAPITAL LETTER ABKHAZIAN CHE WITH DESCENDER");
	genSvg(fontname, "0x04BF", "CYRILLIC SMALL LETTER ABKHAZIAN CHE WITH DESCENDER");
	genSvg(fontname, "0x04C0", "CYRILLIC LETTER PALOCHKA");
	genSvg(fontname, "0x04C1", "CYRILLIC CAPITAL LETTER ZHE WITH BREVE");
	genSvg(fontname, "0x04C2", "CYRILLIC SMALL LETTER ZHE WITH BREVE");
	genSvg(fontname, "0x04C3", "CYRILLIC CAPITAL LETTER KA WITH HOOK");
	genSvg(fontname, "0x04C4", "CYRILLIC SMALL LETTER KA WITH HOOK");
	genSvg(fontname, "0x04C5", "CYRILLIC CAPITAL LETTER EL WITH TAIL");
	genSvg(fontname, "0x04C6", "CYRILLIC SMALL LETTER EL WITH TAIL");
	genSvg(fontname, "0x04C7", "CYRILLIC CAPITAL LETTER EN WITH HOOK");
	genSvg(fontname, "0x04C8", "CYRILLIC SMALL LETTER EN WITH HOOK");
	genSvg(fontname, "0x04C9", "CYRILLIC CAPITAL LETTER EN WITH TAIL");
	genSvg(fontname, "0x04CA", "CYRILLIC SMALL LETTER EN WITH TAIL");
	genSvg(fontname, "0x04CB", "CYRILLIC CAPITAL LETTER KHAKASSIAN CHE");
	genSvg(fontname, "0x04CC", "CYRILLIC SMALL LETTER KHAKASSIAN CHE");
	genSvg(fontname, "0x04CD", "CYRILLIC CAPITAL LETTER EM WITH TAIL");
	genSvg(fontname, "0x04CE", "CYRILLIC SMALL LETTER EM WITH TAIL");
	genSvg(fontname, "0x04CF", "CYRILLIC SMALL LETTER PALOCHKA");
	genSvg(fontname, "0x04D0", "CYRILLIC CAPITAL LETTER A WITH BREVE");
	genSvg(fontname, "0x04D1", "CYRILLIC SMALL LETTER A WITH BREVE");
	genSvg(fontname, "0x04D2", "CYRILLIC CAPITAL LETTER A WITH DIAERESIS");
	genSvg(fontname, "0x04D3", "CYRILLIC SMALL LETTER A WITH DIAERESIS");
	genSvg(fontname, "0x04D4", "CYRILLIC CAPITAL LIGATURE A IE");
	genSvg(fontname, "0x04D5", "CYRILLIC SMALL LIGATURE A IE");
	genSvg(fontname, "0x04D6", "CYRILLIC CAPITAL LETTER IE WITH BREVE");
	genSvg(fontname, "0x04D7", "CYRILLIC SMALL LETTER IE WITH BREVE");
	genSvg(fontname, "0x04D8", "CYRILLIC CAPITAL LETTER SCHWA");
	genSvg(fontname, "0x04D9", "CYRILLIC SMALL LETTER SCHWA");
	genSvg(fontname, "0x04DA", "CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS");
	genSvg(fontname, "0x04DB", "CYRILLIC SMALL LETTER SCHWA WITH DIAERESIS");
	genSvg(fontname, "0x04DC", "CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS");
	genSvg(fontname, "0x04DD", "CYRILLIC SMALL LETTER ZHE WITH DIAERESIS");
	genSvg(fontname, "0x04DE", "CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS");
	genSvg(fontname, "0x04DF", "CYRILLIC SMALL LETTER ZE WITH DIAERESIS");
	genSvg(fontname, "0x04E0", "CYRILLIC CAPITAL LETTER ABKHAZIAN DZE");
	genSvg(fontname, "0x04E1", "CYRILLIC SMALL LETTER ABKHAZIAN DZE");
	genSvg(fontname, "0x04E2", "CYRILLIC CAPITAL LETTER I WITH MACRON");
	genSvg(fontname, "0x04E3", "CYRILLIC SMALL LETTER I WITH MACRON");
	genSvg(fontname, "0x04E4", "CYRILLIC CAPITAL LETTER I WITH DIAERESIS");
	genSvg(fontname, "0x04E5", "CYRILLIC SMALL LETTER I WITH DIAERESIS");
	genSvg(fontname, "0x04E6", "CYRILLIC CAPITAL LETTER O WITH DIAERESIS");
	genSvg(fontname, "0x04E7", "CYRILLIC SMALL LETTER O WITH DIAERESIS");
	genSvg(fontname, "0x04E8", "CYRILLIC CAPITAL LETTER BARRED O");
	genSvg(fontname, "0x04E9", "CYRILLIC SMALL LETTER BARRED O");
	genSvg(fontname, "0x04EA", "CYRILLIC CAPITAL LETTER BARRED O WITH DIAERESIS");
	genSvg(fontname, "0x04EB", "CYRILLIC SMALL LETTER BARRED O WITH DIAERESIS");
	genSvg(fontname, "0x04EC", "CYRILLIC CAPITAL LETTER E WITH DIAERESIS");
	genSvg(fontname, "0x04ED", "CYRILLIC SMALL LETTER E WITH DIAERESIS");
	genSvg(fontname, "0x04EE", "CYRILLIC CAPITAL LETTER U WITH MACRON");
	genSvg(fontname, "0x04EF", "CYRILLIC SMALL LETTER U WITH MACRON");
	genSvg(fontname, "0x04F0", "CYRILLIC CAPITAL LETTER U WITH DIAERESIS");
	genSvg(fontname, "0x04F1", "CYRILLIC SMALL LETTER U WITH DIAERESIS");
	genSvg(fontname, "0x04F2", "CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE");
	genSvg(fontname, "0x04F3", "CYRILLIC SMALL LETTER U WITH DOUBLE ACUTE");
	genSvg(fontname, "0x04F4", "CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS");
	genSvg(fontname, "0x04F5", "CYRILLIC SMALL LETTER CHE WITH DIAERESIS");
	genSvg(fontname, "0x04F6", "CYRILLIC CAPITAL LETTER GHE WITH DESCENDER");
	genSvg(fontname, "0x04F7", "CYRILLIC SMALL LETTER GHE WITH DESCENDER");
	genSvg(fontname, "0x04F8", "CYRILLIC CAPITAL LETTER YERU WITH DIAERESIS");
	genSvg(fontname, "0x04F9", "CYRILLIC SMALL LETTER YERU WITH DIAERESIS");
	genSvg(fontname, "0x04FA", "CYRILLIC CAPITAL LETTER GHE WITH STROKE AND HOOK");
	genSvg(fontname, "0x04FB", "CYRILLIC SMALL LETTER GHE WITH STROKE AND HOOK");
	genSvg(fontname, "0x04FC", "CYRILLIC CAPITAL LETTER HA WITH HOOK");
	genSvg(fontname, "0x04FD", "CYRILLIC SMALL LETTER HA WITH HOOK");
	genSvg(fontname, "0x04FE", "CYRILLIC CAPITAL LETTER HA WITH STROKE");
	genSvg(fontname, "0x04FF", "CYRILLIC SMALL LETTER HA WITH STROKE");

	// -=- Unicode Symbols

	genSvg(fontname, "0x2013", "EN DASH");
	genSvg(fontname, "0x2014", "EM DASH");
	genSvg(fontname, "0x2015", "HORIZONTAL BAR");
	genSvg(fontname, "0x2017", "DOUBLE LOW LINE");
	genSvg(fontname, "0x2018", "LEFT SINGLE QUOTATION MARK");
	genSvg(fontname, "0x2019", "RIGHT SINGLE QUOTATION MARK");
	genSvg(fontname, "0x201A", "SINGLE LOW-9 QUOTATION MARK");
	genSvg(fontname, "0x201B", "SINGLE HIGH-REVERSED-9 QUOTATION MARK");
	genSvg(fontname, "0x201C", "LEFT DOUBLE QUOTATION MARK");
	genSvg(fontname, "0x201D", "RIGHT DOUBLE QUOTATION MARK");
	genSvg(fontname, "0x201E", "DOUBLE LOW-9 QUOTATION MARK");
	genSvg(fontname, "0x2020", "DAGGER");
	genSvg(fontname, "0x2021", "DOUBLE DAGGER");
	genSvg(fontname, "0x2022", "BULLET");
	genSvg(fontname, "0x2026", "HORIZONTAL ELLIPSIS");
	genSvg(fontname, "0x2030", "PER MILLE SIGN");
	genSvg(fontname, "0x2032", "PRIME");
	genSvg(fontname, "0x2033", "DOUBLE PRIME");
	genSvg(fontname, "0x2039", "SINGLE LEFT-POINTING ANGLE QUOTATION MARK");
	genSvg(fontname, "0x203A", "SINGLE RIGHT-POINTING ANGLE QUOTATION MARK");
	genSvg(fontname, "0x203C", "DOUBLE EXCLAMATION MARK");
	genSvg(fontname, "0x203E", "OVERLINE");
	genSvg(fontname, "0x2044", "FRACTION SLASH");
	genSvg(fontname, "0x204A", "TIRONIAN ET SIGN");

	// -=- Block Elements

	genSvg(fontname, "0x2580", "UPPER HALF BLOCK");
	genSvg(fontname, "0x2581", "LOWER ONE EIGHTH BLOCK");
	genSvg(fontname, "0x2582", "LOWER ONE QUARTER BLOCK");
	genSvg(fontname, "0x2583", "LOWER THREE EIGHTHS BLOCK");
	genSvg(fontname, "0x2584", "LOWER HALF BLOCK");
	genSvg(fontname, "0x2585", "LOWER FIVE EIGHTHS BLOCK");
	genSvg(fontname, "0x2586", "LOWER THREE QUARTERS BLOCK");
	genSvg(fontname, "0x2587", "LOWER SEVEN EIGHTHS BLOCK");
	genSvg(fontname, "0x2588", "FULL BLOCK");
	genSvg(fontname, "0x2589", "LEFT SEVEN EIGHTHS BLOCK");
	genSvg(fontname, "0x258A", "LEFT THREE QUARTERS BLOCK");
	genSvg(fontname, "0x258B", "LEFT FIVE EIGHTHS BLOCK");
	genSvg(fontname, "0x258C", "LEFT HALF BLOCK");
	genSvg(fontname, "0x258D", "LEFT THREE EIGHTHS BLOCK");
	genSvg(fontname, "0x258E", "LEFT ONE QUARTER BLOCK");
	genSvg(fontname, "0x258F", "LEFT ONE EIGHTH BLOCK");
	genSvg(fontname, "0x2590", "RIGHT HALF BLOCK");
	genSvg(fontname, "0x2591", "LIGHT SHADE");
	genSvg(fontname, "0x2592", "MEDIUM SHADE");
	genSvg(fontname, "0x2593", "DARK SHADE");
	genSvg(fontname, "0x2594", "UPPER ONE EIGHTH BLOCK");
	genSvg(fontname, "0x2595", "RIGHT ONE EIGHTH BLOCK");
	genSvg(fontname, "0x2596", "QUADRANT LOWER LEFT");
	genSvg(fontname, "0x2597", "QUADRANT LOWER RIGHT");
	genSvg(fontname, "0x2598", "QUADRANT UPPER LEFT");
	genSvg(fontname, "0x2599", "QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT");
	genSvg(fontname, "0x259A", "QUADRANT UPPER LEFT AND LOWER RIGHT");
	genSvg(fontname, "0x259B", "QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT");
	genSvg(fontname, "0x259C", "QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT");
	genSvg(fontname, "0x259D", "QUADRANT UPPER RIGHT");
	genSvg(fontname, "0x259E", "QUADRANT UPPER RIGHT AND LOWER LEFT");
	genSvg(fontname, "0x259F", "QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT");

	// -=- Geometric Shapes

	genSvg(fontname, "0x25A0", "BLACK SQUARE");
	genSvg(fontname, "0x25A1", "WHITE SQUARE");
	genSvg(fontname, "0x25A2", "WHITE SQUARE WITH ROUNDED CORNERS");
	genSvg(fontname, "0x25A3", "WHITE SQUARE CONTAINING SMALL BLACK SQUARE");
	genSvg(fontname, "0x25A4", "SQUARE WITH HORIZONTAL FILL");
	genSvg(fontname, "0x25A5", "SQUARE WITH VERTICAL FILL");
	genSvg(fontname, "0x25A6", "SQUARE WITH ORTHOGONAL CROSSHATCH FILL");
	genSvg(fontname, "0x25A7", "SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL");
	genSvg(fontname, "0x25A8", "SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL");
	genSvg(fontname, "0x25A9", "SQUARE WITH DIAGONAL CROSSHATCH FILL");
	genSvg(fontname, "0x25AA", "BLACK SMALL SQUARE");
	genSvg(fontname, "0x25AB", "WHITE SMALL SQUARE");
	genSvg(fontname, "0x25AC", "BLACK RECTANGLE");
	genSvg(fontname, "0x25AD", "WHITE RECTANGLE");
	genSvg(fontname, "0x25AE", "BLACK VERTICAL RECTANGLE");
	genSvg(fontname, "0x25AF", "WHITE VERTICAL RECTANGLE");
	genSvg(fontname, "0x25B0", "BLACK PARALLELOGRAM");
	genSvg(fontname, "0x25B1", "WHITE PARALLELOGRAM");
	genSvg(fontname, "0x25B2", "BLACK UP-POINTING TRIANGLE");
	genSvg(fontname, "0x25B3", "WHITE UP-POINTING TRIANGLE");
	genSvg(fontname, "0x25B4", "BLACK UP-POINTING SMALL TRIANGLE");
	genSvg(fontname, "0x25B5", "WHITE UP-POINTING SMALL TRIANGLE");
	genSvg(fontname, "0x25B6", "BLACK RIGHT-POINTING TRIANGLE");
	genSvg(fontname, "0x25B7", "WHITE RIGHT-POINTING TRIANGLE");
	genSvg(fontname, "0x25B8", "BLACK RIGHT-POINTING SMALL TRIANGLE");
	genSvg(fontname, "0x25B9", "WHITE RIGHT-POINTING SMALL TRIANGLE");
	genSvg(fontname, "0x25BA", "BLACK RIGHT-POINTING POINTER");
	genSvg(fontname, "0x25BB", "WHITE RIGHT-POINTING POINTER");
	genSvg(fontname, "0x25BC", "BLACK DOWN-POINTING TRIANGLE");
	genSvg(fontname, "0x25BD", "WHITE DOWN-POINTING TRIANGLE");
	genSvg(fontname, "0x25BE", "BLACK DOWN-POINTING SMALL TRIANGLE");
	genSvg(fontname, "0x25BF", "WHITE DOWN-POINTING SMALL TRIANGLE");
	genSvg(fontname, "0x25C0", "BLACK LEFT-POINTING TRIANGLE");
	genSvg(fontname, "0x25C1", "WHITE LEFT-POINTING TRIANGLE");
	genSvg(fontname, "0x25C2", "BLACK LEFT-POINTING SMALL TRIANGLE");
	genSvg(fontname, "0x25C3", "WHITE LEFT-POINTING SMALL TRIANGLE");
	genSvg(fontname, "0x25C4", "BLACK LEFT-POINTING POINTER");
	genSvg(fontname, "0x25C5", "WHITE LEFT-POINTING POINTER");
	genSvg(fontname, "0x25C6", "BLACK DIAMOND");
	genSvg(fontname, "0x25C7", "WHITE DIAMOND");
	genSvg(fontname, "0x25C8", "WHITE DIAMOND CONTAINING SMALL BLACK DIAMOND");
	genSvg(fontname, "0x25C9", "FISHEYE");
	genSvg(fontname, "0x25CA", "LOZENGE");
	genSvg(fontname, "0x25CB", "WHITE CIRCLE");
	genSvg(fontname, "0x25CC", "DOTTED CIRCLE");
	genSvg(fontname, "0x25CD", "CIRCLE WITH VERTICAL FILL");
	genSvg(fontname, "0x25CE", "BULLSEYE");
	genSvg(fontname, "0x25CF", "BLACK CIRCLE");
	genSvg(fontname, "0x25D0", "CIRCLE WITH LEFT HALF BLACK");
	genSvg(fontname, "0x25D1", "CIRCLE WITH RIGHT HALF BLACK");
	genSvg(fontname, "0x25D2", "CIRCLE WITH LOWER HALF BLACK");
	genSvg(fontname, "0x25D3", "CIRCLE WITH UPPER HALF BLACK");
	genSvg(fontname, "0x25D4", "CIRCLE WITH UPPER RIGHT QUADRANT BLACK");
	genSvg(fontname, "0x25D5", "CIRCLE WITH ALL BUT UPPER LEFT QUADRANT BLACK");
	genSvg(fontname, "0x25D6", "LEFT HALF CIRCLE BLACK");
	genSvg(fontname, "0x25D7", "RIGHT HALF BLACK CIRCLE");
	genSvg(fontname, "0x25D8", "INVERSE BULLET");
	genSvg(fontname, "0x25D9", "INVERSE WHITE CIRCLE");
	genSvg(fontname, "0x25DA", "UPPER HALF INVERSE WHITE CIRCLE");
	genSvg(fontname, "0x25DB", "LOWER HALF INVERSE WHITE CIRCLE");
	genSvg(fontname, "0x25DC", "UPPER LEFT QUADRANT CIRCULAR ARC");
	genSvg(fontname, "0x25DD", "UPPER RIGHT QUADRANT CIRCULAR ARC");
	genSvg(fontname, "0x25DE", "LOWER RIGHT QUADRANT CIRCULAR ARC");
	genSvg(fontname, "0x25DF", "LOWER LEFT QUADRANT CIRCULAR ARC");
	genSvg(fontname, "0x25E0", "UPPER HALF CIRCLE");
	genSvg(fontname, "0x25E1", "LOWER HALF CIRCLE");
	genSvg(fontname, "0x25E2", "BLACK LOWER RIGHT TRIANGLE");
	genSvg(fontname, "0x25E3", "BLACK LOWER LEFT TRIANGLE");
	genSvg(fontname, "0x25E4", "BLACK UPPER LEFT TRIANGLE");
	genSvg(fontname, "0x25E5", "BLACK UPPER RIGHT TRIANGLE");
	genSvg(fontname, "0x25E6", "WHITE BULLET");
	genSvg(fontname, "0x25E7", "SQUARE WITH LEFT HALF BLACK");
	genSvg(fontname, "0x25E8", "SQUARE WITH RIGHT HALF BLACK");
	genSvg(fontname, "0x25E9", "SQUARE WITH UPPER LEFT DIAGONAL HALF BLACK");
	genSvg(fontname, "0x25EA", "SQUARE WITH LOWER RIGHT DIAGONAL HALF BLACK");
	genSvg(fontname, "0x25EB", "WHITE SQUARE WITH VERTICAL BISECTING LINE");
	genSvg(fontname, "0x25EC", "WHITE UP-POINTING TRIANGLE WITH DOT");
	genSvg(fontname, "0x25ED", "UP-POINTING TRIANGLE WITH LEFT HALF BLACK");
	genSvg(fontname, "0x25EE", "UP-POINTING TRIANGLE WITH RIGHT HALF BLACK");
	genSvg(fontname, "0x25EF", "LARGE CIRCLE");
	genSvg(fontname, "0x25F0", "WHITE SQUARE WITH UPPER LEFT QUADRANT");
	genSvg(fontname, "0x25F1", "WHITE SQUARE WITH LOWER LEFT QUADRANT");
	genSvg(fontname, "0x25F2", "WHITE SQUARE WITH LOWER RIGHT QUADRANT");
	genSvg(fontname, "0x25F3", "WHITE SQUARE WITH UPPER RIGHT QUADRANT");
	genSvg(fontname, "0x25F4", "WHITE CIRCLE WITH UPPER LEFT QUADRANT");
	genSvg(fontname, "0x25F5", "WHITE CIRCLE WITH LOWER LEFT QUADRANT");
	genSvg(fontname, "0x25F6", "WHITE CIRCLE WITH LOWER RIGHT QUADRANT");
	genSvg(fontname, "0x25F7", "WHITE CIRCLE WITH UPPER RIGHT QUADRANT");
	genSvg(fontname, "0x25F8", "UPPER LEFT TRIANGLE");
	genSvg(fontname, "0x25F9", "UPPER RIGHT TRIANGLE");
	genSvg(fontname, "0x25FA", "LOWER-LEFT TRIANGLE");
	genSvg(fontname, "0x25FB", "WHITE MEDIUM SQUARE");
	genSvg(fontname, "0x25FC", "BLACK MEDIUM SQUARE");
	genSvg(fontname, "0x25FD", "WHITE MEDIUM SMALL SQUARE");
	genSvg(fontname, "0x25FE", "BLACK MEDIUM SMALL SQUARE");
	genSvg(fontname, "0x25FF", "LOWER RIGHT TRIANGLE");
}

int main(int argc, char * argv[]) {
	if (argc < 2) {
		std::cerr << "Usage: " << argv[0] << " font.ttf\n" << std::endl
			<< "Output: ./Output/*.svg" << std::endl;
		exit(1);
	}

	create_svgs(argv[1]);

	return 0;
}
